### ISSUE TITLE
[BUG] srt-live-transmit-win64-noencryption.exe (Windows) dropping UDP packets

### ISSUE THREAD

**Issue by Peterdoo** [Haivision/srt#1642] opened 2020-11-06 12:13 UTC
When I use srt-live-transmit-win64-noencryption (SRT Library version: 1.4.2) to receive UDP packets and send them out via SRT, not all UDP packets are sent out. Wireshark will show the received UDP packets but some of them are simply not present in the SRT output. The statistics shows no missing/dropped packets. So there are UDP packets that arrive fine to srt-live-transmit-win64-noencryption, but are not present after the SRT path without any notification of packet loss neither in the SRT sender nor in the SRT receiver.

To Reproduce:
srt-live-transmit-win64-noencryption.exe -v -s:2000 udp://239.192.1.251:1234 srt://6600
Capture port 6600 and port 1234 in two separate instances of Wireshark.

This is what I can see in Wireshark on the places where packets are dropped:
![image](https://user-images.githubusercontent.com/33329671/98363920-16ebc000-2030-11eb-9e43-d35667a076bf.png)

The first UDP packet with the size of 1358 translates to msgno 2316499 and is transmitted normally via SRT.
The second UDP packet wit the size of 1358 translates to msgno 2316500 and is not transmitted via SRT. It is only transmitted later after receiving UMSG_LOSSREPORT for that packet from the receiver.
The next six received UDP packets are simply ignored. No msgno is assigned to them and they are not sent out via SRT. No drop counter is incremented.
The last UDP packet with the size of 794 translates to msgno 2316501 and is transmitted normally via SRT.
Then it continues working again for a few minutes without dropping packets.

The SRT receiver indicates one resent packet (msgno 2316500) and no dropped packets, although six UDP packets are missing after the SRT path.

As Wireshark can see those UDP packets, I assume that they are also received by the application srt-live-transmit-win64-noencryption and get lost somehow inside the application.

Running on Windows 10 20H2 physical machine.
 - SRT Version: 1.4.2

**Comment by Peterdoo** [comment] 2020-11-06 13:00
I have tested the same UDP->SRT scenario with srt-live-transmit under Linux. There are no dropped packets there. Only Windows version seems to be dropping packets.

**Comment by maxsharabayko** [comment] 2020-11-06 14:13
Due to #973. See #974.

**Comment by Peterdoo** [comment] 2020-11-06 21:06
I have built srt-live-transmit for Windows with your today's patch. I am sorry to tell that the problem still exists.
Obviously #974 does not resolve the mentioned problem of dropping packets.

**Comment by maxsharabayko** [comment] 2020-11-09 11:21
The fix in PR #974 only waits for 50ms for sending operation to complete. If sending still has not succeeded, then the packet will be lost. See [this line](https://github.com/maxsharabayko/srt/blob/hotfix/wsasend-overlapped/srtcore/channel.cpp#L665) with `WSAWaitForMultipleEvents`.

You can change the timeoit to `WSA_INFINITE`, then no loss on sending is expected.

However, there is a dilemma around this kind of waiting.
In live streaming it does not make sense to wait forever. There is a certain time interval when sending a packet still makes sense. Otherwise it may become too late to send it because you could not maintain the end-to-end streaming latency.

50 ms is a random value used for experimenting. A better value might be related to [`SRTO_LATENCY`](https://github.com/Haivision/srt/blob/master/docs/APISocketOptions.md#SRTO_LATENCY) value or maybe even [`SRTO_SNDDROPDELAY`](https://github.com/Haivision/srt/blob/master/docs/APISocketOptions.md#SRTO_SNDDROPDELAY).

**Comment by Peterdoo** [comment] 2020-11-09 22:16
In my above example there is only one SRT packet which has not been sent out. Bitrate is around 6 Mbit/s, so shouldn't be a problem for Windows to handle it without any waiting on sending operations. Let's assume that because the app has just sent UMSG_ACKACK, Windows needs some time to send the other UDP packet which the app delivered at the same time. However, definitely there is no reason for Windows to need more than 50 ms to send that small packet while the computer's CPU use is at 3% and network use at less than 1%. I see no reason for increasing the timeout.

I might agree that #974 could fix that one missing packet. I haven't done another recording to verify it.

However in my above example there are six UDP packets received by the app which are simply ignored. No msgno is assigned to them and they are not sent out via SRT. If the msgno is not incremented, I assume that the app does not even try to send out those packets. Before #974 the app simply ignores the fact that Windows has rejected to send out a packet. So there should be no other side effects visible than that a packet is missing on the output. I don't see any reason why the msgno incrementing would stop when a packet is not sent out. The app does not know anything about it no being sent out as it is not checking the result of the send operation (before #974).

So I agree that #974 might fix one of the 7 missing packets from my above example, but I don't see any reason why #974 would fix the other 6 packets that are missing and which do not increment msgno. My test with the app built with #974 patch included, running on an almost idle Windows showed that packets are still dropped. There must be a different reason which causes dropping packets in a way that the app does not even try to send them out.

**Comment by maxsharabayko** [comment] 2020-11-10 09:31
Ok, so there are two issues here.

1. SRT packet sending on Windows, addressed in PR #974.

> The second UDP packet wit the size of 1358 translates to msgno 2316500 and is not transmitted via SRT. It is only transmitted later after receiving UMSG_LOSSREPORT for that packet from the receiver.

2. `srt-live-transmit` loses some packets on UDP input `udp://239.192.1.251:1234`. Wireshark confirms the packet has arrived, right?

Please try `-buffering:1` command line option to disable buffering of incomming UDP packets.
Please also read [this note](https://github.com/Haivision/srt/blob/master/docs/srt-live-transmit.md#udp-performance) on UDP performance of srt-live-transmit, although it is related to high bitrates.

You could also check `srt-test-live` (configure SRT project with `-DENABLE_TESTING=ON` in cmake) or [`srt-xtransmit`](https://github.com/maxsharabayko/srt-xtransmit). They have a bit different UDP processing and may resolve the issue.

**Comment by maxsharabayko** [comment] 2024-04-18 13:46
Closing as inactive with the assumption the issue is resolved by [this suggestion](https://github.com/Haivision/srt/issues/1642#issuecomment-724581063).

**Closed by maxsharabayko** 2024-04-18 13:46 UTC
Labels: Type: Bug, [core]
