### ISSUE TITLE
Should undecryptable packets arrive at the epoll?

### ISSUE THREAD

**Issue by Chardrazle** [Haivision/srt#2503] opened 2022-10-28 15:46 UTC
We are currently upgrading from version 1.4.3 to 1.5.0, and just wanted to check if there were any behavioural changes that might explain what we see - before delving deeper into the investigation.
We have some (relatively) simple unit-tests that set up a local sender/receiver.  One of those tests is for encryption and has a missing passphrase in the receiver.
In the version 1.4.3 build the packet does not make it past the _epoll_, but in the 1.5.0 version it does.  So an undecryptable packet is presented to the handler.

In both cases the logs can be seen to:
```
.../srt/srt-src/srtcore/crypto.cpp(822)	ERROR	decrypt	/SRT:RcvQ:w1*E:SRT.cn: SECURITY STATUS: NOSECRET - can't decrypt w_packet.
.../srt/srt-src/srtcore/crypto.cpp(824)	TRACE	decrypt	/SRT:RcvQ:w1 D:SRT.cn: Packet still not decrypted, status=NOSECRET - dropping size=1456
.../srt/srt-src/srtcore/core.cpp(10170)	TRACE	processData	/SRT:RcvQ:w1 D:SRT.qr: @29409669:ERROR: packet not decrypted, dropping data.
```

At first this looked like symptoms similar to issue #1977, but that appears to be for earlier versions.
(The `SRTO_ENFORCEDENCRYPTION` is switched off, though.)

When trying to identify a difference, a preliminary trace through the code found that the iteration loop in _epoll.cpp_ (~607):
`for (CEPollDesc::enotice_t::iterator it = ed.enotice_begin(), it_next = it; it != ed.enotice_end(); it = it_next)`
was not entered for the 1.4.3 version, so the `total` counter was not incremented.
There is a 'notice' in this container for the 1.5.0 -based build, resulting in a non-zero return.

Of course, this may just be highlighting that we're doing something wrong elsewhere, hence the question rather than issue :)

**Comment by Chardrazle** [comment] 2022-11-01 18:11
I've modified, well right now it's just a horrible kludge of, the test code you mentioned.
(The test is run with _--gtest_filter_, as it's so hard-coded at the moment.)
The test case _D.3_ is the closest to what we have (from the matrix).
In our system we have threads for the sender and receiver, with epoll instances on both.  So, to roughly behave the same, after the current connection part of the test executes (in `TestConnect`) I've made the code create two new epoll instances, and link those to the sender (`m_caller_socket`) and receiver (`accepted_socket`), respectively.  (We use `srt_epoll_wait`).
I then send a single packet, wait a while, and call the epoll associated with the receiver.  This reports the event, and a subsequent `srt_recvmsg2` acquires the (still encrypted) packet data.

I copied the kludge into the 1.4.3 code and the epoll does not report the event.  So it looks like something changed between versions.

**Comment by Chardrazle** [comment] 2022-11-06 22:59
In light of the above findings, this is now a suspected regression.  Can the label be updated, or should another issue be raised?

**Comment by maxsharabayko** [comment] 2023-01-09 11:41
@Chardrazle Could you please share the test you have to reproduce the issue?

### TODO

- [ ] Check if #2599 (dropping all kinds of undecrypted packets) changes this behavior even further.

**Comment by Chardrazle** [comment] 2023-01-09 16:40
As mentioned, the test code was hacked just for the specific case.  But, FWIW, the attached diff can be applied.
`patch test_enforced_encryption.cpp 2503_srt_3pp_143_150_kludge.diff.txt`
[2503_srt_3pp_143_150_kludge.diff.txt](https://github.com/Haivision/srt/files/10375098/2503_srt_3pp_143_150_kludge.diff.txt)

It's likely the code (incorrectly) breaks other unit-tests because it was purely based on exercising the _D.3_ matrix case.
I.e. `./test-srt --gtest_filter="*CASE_D_3*No*"`
The diff can be applied to both the 1.5.0 and 1.4.3 code, to see the different behaviour.

We have now moved over to `SRTO_ENCFORCEDENCRYPTION` enabled, so have avoided the issue.

**Comment by Chardrazle** [comment] 2023-01-13 12:31
Yes, I can confirm the same findings as yourself :+1: 
I cannot recall if I ever tested against latest _master_; I probably only tried the tagged versions.
I just tried the nearest commit to the date I raised the defect and that shows the issue.  So it looks like the fix went in some time between then and now.

**Comment by ethouris** [comment] 2023-01-16 15:53
Ok, I'm closing this issue then - there's nothing more to do, and it is still visible as required the 1.5.1 release.

**Closed by ethouris** 2023-01-16 15:53 UTC
Labels: Type: Bug, [core]

**Comment by ethouris** [comment] 2023-01-23 13:26
Just for the record: the #2599 PR has fixed the problem (likely, that is, maybe the fix wasn't exactly intended for this problem, but it did fix it).

The change was related to the new receiver buffer logics.

With the old receiver buffer logics packets that failed to get decrypted had the encryption flags not cleared and as such the packet didn't constitute any valid data and hence it wasn't also triggering read-readiness.

In the new receiver buffer the encryption logics have been taken away and therefore the decryption failure had to be programmed differently - that is, undecrypted packets (after adding to the buffer) had to be removed from the buffer, and not only themselves, but the whole message, if the packet was a part of a message.
