### ISSUE TITLE
stransmit  dropping client connections - recvmsg: [-1000] Unknown error

### ISSUE THREAD

**Issue by SKIPADoDev** [Haivision/srt#14] opened 2017-05-01 11:46 UTC
Somewhere between 1 minute and an hour stransmit server/receiver drops the client connection.
The process stays running and the port is still blocking, 
but it will not accept reconnection attempts fron the client/caller.

On the encoder client I get one of these two errors:
107 (Transport endpoint is not connected)
104 (connection reset by peer)

the stransmit error is always the same:
FAILURE
recvmsg: [-1000] Unknown error.

I think it comes from stransmit.cpp line 1210 in bytevector READ; stat == SRT_ERROR.

Can I do something to avoid this error, 
or can we catch the condition and recover the stream?

```
# stransmit -k -v srt://xx.xx.xx.xx:9100?mode=server udp://xx.xx.xx.xx:9110 >> /var/log/stransmit.`date +%s`.log 2>&1 &
    [1] 18048
# netstat -na | grep 9100
udp        0      0 xx.xx.xx.xx:9100      0.0.0.0:*       
# head stransmit.1493555817.log
Parameters:
        mode = 'server'
Opening SRT source server(blocking) on xx.xx.xx.xx:9100
PRE: blocking mode set: 1 timeout 0
Binding a server on xx.xx.xx.xx:9100 ... listen...  accept...  connected.
STARTING TRANSMISSION: 'srt://xx.xx.xx.xx:9100?mode=server' --> 'udp://xx.xx.xx.xx:9110'
 << 376  ->   sent
 << 376  ->   sent

### a few minutes later...
### encoder 'send buffer' and 'retransmit rate' spike high
### encoder state is disconnected: Last Error: 107 (Transport endpoint is not connected)

# tail -2 stransmit.1493555817.log
    FAILURE
    recvmsg: [-1000] Unknown error.
# ps -aef | grep stransmit
root     18048 15889  2 14:36 pts/2    00:00:09 stransmit -k -v srt://xx.xx.xx.xx:9100?mode=server udp://xx.xx.xx.xx:9110
# netstat -na | grep 9100
udp   427072      0 xx.xx.xx.xx:9100      0.0.0.0:*
```

**Comment by ethouris** [comment] 2017-05-02 11:11
It looks like something that might be hard to reproduce. I'd need some more details about what happened that caused this "retransmit rate" spike high. Important because it still might have happened that your network was down for 1 minute and in this case SRT can't do much to maintain the connection.

This -1000 error (Unknown) normally happens in SRT library when it catches an unknown kind of exception. SRT uses (as derived from UDT) the CUDTException class only. Any other exception is treated as unknown and causes API error.

Such an exception can be thrown from an application, if it throws it from a signal handler - and `stransmit` does it in two cases:

* when you press Ctrl-C on the console, which will turn into `SIGINT`, the handler will cause any pending call to `connect` or `accept` to be interrupted by an exception (that's the only way how it can be interrupted, actually)
* when nothing happens for the length of the _timeout_, the application will interrupt - there's a call to a system function, `alarm`, which will cause an alarm call to be done; the `stransmit` application throws an exception in order to simulate an interrupted system call. By default this timeout is 30 seconds. You can turn off this behavior by specifying the `-t:-1` option (setting the timeout to -1 which means infinite - this turns off the "watchdog")

The `-k` option is to enforce stransmit to make a coredump when some interrupt reason occurs - that's usually for developers to track down the reason. 

I found something that might cause the problem with proper releasing of the UDP port, and therefore inability to bind to that port again - after the failure the socket should be closed manually because the `SrtCommon::Open*()` functions are called effectively from the constructors of `SrtSource` and `SrtTarget` and therefore the closing of the socket normally done in destructor won't happen. Although the system is supposed to release UDP ports occuppied by an application, for some time it keeps them still open (or, more precisely, dangling).

**Comment by SKIPADoDev** [comment] 2017-05-03 19:24
Thanks Ethouris for explaining the signal handler and the hanging port problem.

So I tested stransmit on a bunch of machines:

MakitoX TSoverSRT => SRT://stransmit:9100?mode=server => UDP://:9110
They all ran for hours without error or dumping
```
   network  availBW  lat  platform           Result
1. localLan 1000Mbps  0ms ubu 14.04.5 trusty (Runs)
2. localLan 1000Mbps  0ms ubu 16.04.2 xenial (Runs)
3. Internet  700Mbps 12ms ubu 16.04.2 xenial (Runs)
4. Internet  700Mbps 15ms ubu 14.04.5 trusty (Runs)
5. Internet  700Mbps  5ms Deb  7      wheezy (Runs)
```
My original problem from this thread is host #3
The core dump can be reproduced if a wowza stream file binds to 9110 and starts consuming the UDP.
ffmpeg also dumped stransmit after 25 minutes.. 
ffmpeg -i udp://xx.xx.xx.xx:9110 ffout.TS

stransmit output in both instances:  
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Watchdog bites hangup
```
I tried connecting wowza on host #4 and it ran fine for an hour with no dump, so I need to do more testing.
maybe it is just a host 3 port problem and nothing to do with stransmit...

I also watched a tcpdump on input srt:9100 and found the stream never stopped or stuttered.  
So, the -1000 error (Unknown) is maybe not from the timeout function.

Anyway, is there a time-frame for integrating SRT as an acceptable Wowza input protocol?

**Comment by ethouris** [comment] 2017-06-09 11:27
Not sure about that last question.

The timeout can be changed by using `-t` option (remember COLON after the option name). If you use `-t:-1`, you'll turn off the timeout watchdog completely.

A little troublesome thing in such a solution is that when you need to interrupt a system call, you do some standard thing that interrupts it (any signal, so it can be also set by `alarm()`). In a userspace solution, like this, you'd have to translate it somehow to sending some signal on condition variable, interrupt some threads, release mutexes etc., and this can't be really done on a signal. The only solution that comes to my mind is to give this thing up to the user - the library cannot decide by itself about installing signal handlers because not only will it be acting behind the back of the application, but it will be also unreliable if an application occasionally would like to handle a signal and is unaware of that the library is already doing this.

**Comment by alivardar** [comment] 2017-09-13 11:16
Hi,
When I use adapter paramater in URL I saw that message.
B.R.

**Comment by ethouris** [comment] 2017-09-13 11:18
How exactly do you run stransmit with adapter parameter?

**Comment by alivardar** [comment] 2017-09-13 11:25
Here is run commands for listener and caller 
**Listener:**
root@pikotv3002:/opt/penc/tmp# /opt/penc/sbin/stransmit 'srt://192.168.2.228:10000?adapter=192.168.2.228&mode=listener' 'udp://192.168.2.77:5000?adapter=192.168.2.228' -v
Parameters:
        adapter = '192.168.2.228'
        mode = 'listener'
Opening SRT source listener(blocking) on 192.168.2.228:10000
Binding a server on 192.168.2.228:10000 ... listen...  accept...  connected.
STARTING TRANSMISSION: 'srt://192.168.2.228:10000?adapter=192.168.2.228&mode=listener' --> 'udp://192.168.2.77:5000?adapter=192.168.2.228'
FAILURE
**recvmsg: [-1000] Unknown error.**
SrtCommon: DESTROYING CONNECTION, closing sockets

**Caller:**
/opt/penc/sbin/stransmit 'udp://233.30.30.1:5000?adapter=127.0.0.1' 'srt://192.168.2.228:10000?adapter=192.168.2.227&ipttl=64&latency=60&oheadbw=33' -v
Parameters:
        adapter = '192.168.2.227'
        ipttl = '64'
        latency = '60'
        oheadbw = '33'
Opening SRT target client(blocking) on 192.168.2.228:10000
Connecting to 192.168.2.228:10000 ...  connected.
NOTE: SRT/post::oheadbw=33
STARTING TRANSMISSION: 'udp://233.30.30.1:5000?adapter=127.0.0.1' --> 'srt://192.168.2.228:10000?adapter=192.168.2.227&ipttl=64&latency=60&oheadbw=33'
SrtCommon: DESTROYING CONNECTION, closing sockets

**Comment by ethouris** [comment] 2017-09-13 11:31
Looks like an interesting case. Would you be able to turn on debug logging (-loglevel:debug) and attach the log dump? (Note that it requires to compile either in debug mode or with ENABLE_LOGGING=1)

I can see that you're running the listener weird way. The "host" part in the URI is set as adapter, and the alternative way to set adapter by parameter overrides it, so it only makes sense if you leave "host" empty, in which case also the 'mode' defaults to listener. The simplest way for you should be to put the "adapter" IP as host part in the URI, and only enforce the listener mode by parameter.

But still, even if it's called wrong way, such an error isn't expected.

**Comment by alivardar** [comment] 2017-09-13 12:01
Hi,
Here is log.

Parameters:
        adapter = '192.168.2.228'
        mode = 'listener'
Opening SRT source listener(blocking) on 192.168.2.228:10000
Binding a server on 192.168.2.228:10000 ... listen...  accept...  connected.
STARTING TRANSMISSION: 'srt://192.168.2.228:10000?adapter=192.168.2.228&mode=listener' --> 'udp://192.168.2.77:5000?adapter=192.168.2.228'
14:52:14.114058/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:14.150230/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:15.114150/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:15.183984/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:16.114213/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:16.215995/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:17.114278/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:17.248006/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:18.114339/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:18.284025/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:19.114402/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:19.312024/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:20.114467/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:20.344036/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:21.114531/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:21.372071/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:22.114592/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:22.406230/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:23.114655/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:23.432063/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:24.114721/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:24.468083/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:25.114788/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:25.496089/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:26.114852/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:26.534226/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:27.114913/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:27.568114/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:28.114975/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:28.602227/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:29.115037/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:29.632126/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:30.115101/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:30.664136/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:31.115165/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:31.692155/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:32.115229/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:32.728162/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:33.115292/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:33.752138/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:34.115356/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:34.780186/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:35.115421/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:35.814229/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:36.115485/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:36.848206/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:37.115547/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:37.876212/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:38.115610/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:38.910229/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:39.115672/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:39.946227/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:40.115735/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:40.972246/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:41.115798/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:42.002233/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
14:52:42.115860/stransmit D: SRT.t: recvmsg: DATA COND: expired -- trying to get data anyway
14:52:43.028279/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
FAILURE
recvmsg: [-1000] Unknown error.
SrtCommon: DESTROYING CONNECTION, closing sockets

**Comment by ethouris** [comment] 2017-09-13 18:01
Ah, forgot one thing - the `-v` option should give you also insight into what `stransmit` is doing. This looks like an error that occurred when `stransmit` calls some of the SRT functions. It just doesn't show it without `-v`.

**Comment by alivardar** [comment] 2017-09-18 07:41
We moved our test devices to customer side. When will finished our implementation I will test. Sorry for late answer.

**Comment by alivardar** [comment] 2017-09-26 07:11
Hi,
We testes and solved problem. When we use '@' symbol on caller source address part It is not giving any error and working/ When stransmit cannot read from source it is giving this error message.
Interesting part this multicast IP address block alread defined in our route table list on system. But without @ symbol it can not read from multicast address.

**Working example:**
/opt/penc/sbin/stransmit 'udp://@233.30.30.1:5000?adapter=127.0.0.1' 'srt://192.168.2.228:10000?adapter=192.168.2.227&ipttl=64&latency=60&oheadbw=33'

**Comment by ethouris** [comment] 2017-09-26 08:00
Ah, right. You had a good intuition about the @ character - actually if you want to **read** from a multicast address, the application must first subscribe to the IGMP group, otherwise the router will not redirect packets that were sent to this group. The @ character causes additionally the IGMP subscription before starting reading.

I think this must be explicitly described in some doc.

**Closed** 2019-05-29 13:56 UTC
Labels: Status: Pending, Type: Bug, Type: Question
