### ISSUE TITLE
[BUG] Two minutes of idle link until connection is closed

### ISSUE THREAD

**Issue by maxsharabayko** [Haivision/srt#1833] opened 2021-02-26 13:40 UTC
### Description

Sender-caller finishes sending and closes the connection sending the UMSG_SHUTDOWN message.

Receiver-listener does not receive the shutdown (in this case due to loss in the network).
Packet No. 3972, Time 66.905873 in the network capture attached.

Up until 70,972606 receiver continues sending ACK and LOSSREPORT, likely dropping missing packets.

Starting at 70.972606 receiver starts sending KEEPALIVE packets every 1 s, and sometimes ACK packets.

At 191.806702 the connection is finally shut down by the receiver. So it took 120 seconds to close an idle SRT socket.

P.S. Latency turned out to be not enough for this network, however, it should not affect the logic of closing a connection.

Network capture plus receiver and sender stats:
- [single-1Mbps.zip](https://github.com/Haivision/srt/files/6049860/single-1Mbps.zip)

#### Sender

- Mac OS over WiFi.
- `ENABLE_STDCXX_SYNC = ON`
- SRT commit 6012fdf483e8ddaca53a9f88e34ab5641c549b2a (v1.4.2)
- srt-xtransmit commit [f66de1](https://github.com/maxsharabayko/srt-xtransmit/commit/f66de1f2554eae704945ee0d940953a2ae8a1161) (develop/bonding)
  Date:   Mon Feb 8 17:48:48 2021 +0100
  Fixed reorder distance metric

```
srt-xtransmit generate "srt://192.168.1.91:4201?latency=400" --sendrate 1Mbps --duration 30s
                       --statsfile single-1Mbps-stats-snd.csv --statsfreq 100ms -v

13:17:19.346292 [I] DST URL: srt://192.168.1.91:4201?latency=400
13:17:19.347621 [D] SOCKET::SRT 0x2C68747D ASYNC Connecting to srt://192.168.1.91:4201
13:17:19.892197 [D] SOCKET::SRT 0x2C68747D ASYNC Connected to srt://192.168.1.91:4201
13:17:19.892292 [T] STATS: Added socket 745043069.
13:17:19.892436 [I] PACER sendrate 1000000 bps (inter send interval 10537 us)
13:17:20.893469 [I] GENERATE Sending at 988 kbps
...
13:17:47.920474 [I] GENERATE Sending at 999 kbps
13:17:48.921462 [I] GENERATE Sending at 999 kbps
13:17:49.976559 [D] SOCKET::SRT @745043069 srt::~srt. releasing epolls
13:17:49.976634 [D] SOCKET::SRT 0x2C68747D srt::~srt: closing
```

#### Receiver

- Windows over WiFi (local network)
- `ENABLE_STDCXX_SYNC = ON`
- SRT commit 72b68fcafa2c0854c15632d7947e49fa40775ad1 (v1.4.2)
- srt-xtransmit commit [7a3c71](https://github.com/maxsharabayko/srt-xtransmit/commit/7a3c71072a1a392836ca0bc60bfcce0da47f8315) (develop/bonding)
  Date:   Fri Jan 22 16:22:12 2021 +0100
  Corrected group log a bit

```
.\bin\Debug\srt-xtransmit.exe receive srt://:4201 --statsfile single-1Mbps-stats-rcv.csv --statsfreq 100ms -v
```

<details><summary>APP log (Click to expand/collapse)</summary>
<p>

```shell
13:16:34.450675 [I] SRC URL: srt://:4201
13:16:34.456367 [D] SOCKET::SRT 0x1B5376A6 (srt://:4201) Listening
13:16:34.456904 [D] SOCKET::SRT 0x1B5376A6 (srt://:4201) ASYNC Waiting for incoming connection
13:17:19.104540 [D] SOCKET::SRT 0x1B5376A6 (srt://:4201) Accepted connection 0x1B5376A5
13:17:19.107072 [T] STATS: Added socket 458454693.
13:17:19.871000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779151 delayed for 4.366 ms
13:17:19.903000/T10552!W:SRT.br: RCV-DROPPED 2 packet(s), packet seqno %1602779154 delayed for 4.446 ms
13:17:19.981000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779161 delayed for 8.707 ms
13:17:20.099000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779172 delayed for 11.316 ms
13:17:20.143000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779177 delayed for 1.997 ms
13:17:20.205000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779182 delayed for 11.359 ms
13:17:20.658000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779212 delayed for 148.375 ms
13:17:20.763000/T10552!W:SRT.br: RCV-DROPPED 2 packet(s), packet seqno %1602779220 delayed for 169.385 ms
13:17:20.954000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779240 delayed for 149.839 ms
13:17:20.969000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779247 delayed for 90.529 ms
13:17:21.013000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779253 delayed for 71.544 ms
13:17:21.446000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779274 delayed for 283.387 ms
13:17:21.466000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779280 delayed for 240.174 ms
13:17:22.139000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779307 delayed for 628.802 ms
13:17:22.447000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779337 delayed for 620.773 ms
13:17:22.991000/T10552!W:SRT.br: RCV-DROPPED 21 packet(s), packet seqno %1602779372 delayed for 795.136 ms
13:17:23.022000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779375 delayed for 794.746 ms
13:17:23.245000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779410 delayed for 648.998 ms
13:17:24.095000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779462 delayed for 951.155 ms
13:17:24.117000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779466 delayed for 931.050 ms
13:17:24.131000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779469 delayed for 913.456 ms
13:17:24.471000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779483 delayed for 1105.547 ms
13:17:24.941000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779510 delayed for 1291.456 ms
13:17:25.135000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779518 delayed for 1401.172 ms
13:17:25.581000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779550 delayed for 1510.310 ms
13:17:25.791000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779569 delayed for 1519.394 ms
13:17:26.778000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779628 delayed for 1885.279 ms
13:17:27.054000/T10552!W:SRT.br: RCV-DROPPED 126 packet(s), packet seqno %1602779763 delayed for 738.782 ms
13:17:27.179000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779769 delayed for 799.960 ms
13:17:27.514000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779811 delayed for 692.429 ms
13:17:27.687000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779823 delayed for 739.046 ms
13:17:28.341000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779868 delayed for 919.620 ms
13:17:28.537000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779883 delayed for 957.187 ms
13:17:30.306000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779956 delayed for 1956.939 ms
13:17:30.390000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779960 delayed for 1998.821 ms
13:17:30.404000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779962 delayed for 1992.179 ms
13:17:30.706000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602779989 delayed for 2008.710 ms
13:17:31.043000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780004 delayed for 2188.507 ms
13:17:31.065000/T10552!W:SRT.br: RCV-DROPPED 50 packet(s), packet seqno %1602780056 delayed for 1662.149 ms
13:17:31.101000/T10552!W:SRT.br: RCV-DROPPED 98 packet(s), packet seqno %1602780155 delayed for 654.630 ms
13:17:32.535000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780252 delayed for 1066.480 ms
13:17:33.061000/T10552!W:SRT.br: RCV-DROPPED 2 packet(s), packet seqno %1602780269 delayed for 1413.429 ms
13:17:33.356000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780293 delayed for 1455.723 ms
13:17:33.555000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780305 delayed for 1528.253 ms
13:17:33.674000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780333 delayed for 1352.337 ms
13:17:34.272000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780358 delayed for 1686.749 ms
13:17:34.274000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780360 delayed for 1668.065 ms
13:17:34.552000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780373 delayed for 1808.525 ms
13:17:34.843000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780393 delayed for 1888.881 ms
13:17:34.993000/T10552!W:SRT.br: RCV-DROPPED 2 packet(s), packet seqno %1602780412 delayed for 1838.726 ms
13:17:35.007000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780416 delayed for 1811.016 ms
13:17:35.231000/T10552!W:SRT.br: RCV-DROPPED 112 packet(s), packet seqno %1602780546 delayed for 664.884 ms
13:17:35.315000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780561 delayed for 590.633 ms
13:17:35.778000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780587 delayed for 779.799 ms
13:17:36.123000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780607 delayed for 914.195 ms
13:17:36.710000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780630 delayed for 1259.351 ms
13:17:37.001000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780637 delayed for 1475.731 ms
13:17:37.075000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780644 delayed for 1476.496 ms
13:17:37.324000/T10552!W:SRT.br: RCV-DROPPED 88 packet(s), packet seqno %1602780742 delayed for 693.216 ms
13:17:37.543000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780762 delayed for 701.554 ms
13:17:37.758000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780791 delayed for 610.887 ms
13:17:37.879000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780800 delayed for 636.956 ms
13:17:38.072000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780817 delayed for 650.701 ms
13:17:39.502000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780877 delayed for 1448.174 ms
13:17:39.947000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780897 delayed for 1682.936 ms
13:17:40.105000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780905 delayed for 1755.795 ms
13:17:40.175000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780908 delayed for 1794.397 ms
13:17:40.817000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780944 delayed for 2057.648 ms
13:17:41.041000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602780955 delayed for 2165.188 ms
13:17:41.584000/T10552!W:SRT.br: RCV-DROPPED 142 packet(s), packet seqno %1602781134 delayed for 822.379 ms
13:17:41.701000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602781142 delayed for 854.881 ms
13:17:41.794000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602781148 delayed for 884.898 ms
13:17:42.202000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602781189 delayed for 860.796 ms
13:17:42.214000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602781194 delayed for 819.832 ms
13:17:42.228000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602781196 delayed for 813.147 ms
13:17:42.587000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602781217 delayed for 950.967 ms
13:17:45.428000/T10552!W:SRT.br: RCV-DROPPED 26 packet(s), packet seqno %1602781429 delayed for 1558.116 ms
13:17:45.543000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602781431 delayed for 1651.669 ms
13:17:45.566000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602781434 delayed for 1643.139 ms
13:17:45.675000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602781448 delayed for 1604.974 ms
13:17:46.665000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602781524 delayed for 1793.485 ms
13:17:46.870000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602781543 delayed for 1799.095 ms
13:17:47.128000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602781559 delayed for 1888.080 ms
13:17:47.144000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602781561 delayed for 1883.177 ms
13:17:47.311000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602781583 delayed for 1818.247 ms
13:17:47.380000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602781592 delayed for 1792.709 ms
13:17:47.553000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602781604 delayed for 1839.217 ms
13:17:47.570000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602781609 delayed for 1803.379 ms
13:17:47.606000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602781614 delayed for 1786.648 ms
13:17:47.885000/T10552!W:SRT.br: RCV-DROPPED 96 packet(s), packet seqno %1602781723 delayed for 917.288 ms
13:17:48.084000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602781734 delayed for 999.751 ms
13:17:48.724000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602781758 delayed for 1386.812 ms
13:17:48.969000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602781773 delayed for 1474.477 ms
13:17:50.966000/T10552!W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %1602781833 delayed for 2839.337 ms
13:19:54.112024 [D] SOCKET::SRT 0x1B5376A5 read::recv ERROR 2001 Connection was broken
13:19:54.113969 [W] RECEIVE read::recv: Connection was broken
13:19:54.115873 [D] SOCKET::SRT @458454694 srt::~srt. releasing epolls
13:19:54.117269 [D] SOCKET::SRT 0x1B5376A6 srt::~srt: closing
13:19:54.206595 [D] SOCKET::SRT @458454693 srt::~srt. releasing epolls
13:19:54.208969 [D] SOCKET::SRT 0x1B5376A5 srt::~srt: closing
```
</p></details>

#### Network Impairments

On Windows (receiver side)

![image](https://user-images.githubusercontent.com/12700120/109306497-8d126d80-783f-11eb-989e-6cdca8d00c92.png)

**Comment by J-Rogmann** [comment] 2021-04-15 07:32
I repeated the test on Flip/Flop using `xtransmit` commit `f66de1` and SRT submodule version `6012fdf`.

On LANforge I applied 50ms delay in each direction and 5% bi-directional packet loss.

In all test runs the connection was closed within a few seconds on the other side.

I also tried in my home network with exact version on Linux and a 1.4.2 on windows and couldn't reproduce it either. (delay and packet loss generated with netem).

**Result: not reproducible**

**Comment by mbakholdina** [comment] 2021-04-15 10:06
@J-Rogmann Thanks for the attempt in reproducing the issue. Test results show that the issue can't be easily reproduced and we don't have exact test steps and circumstances to follow, however @maxsharabayko was able to catch the problem previously. 

I am closing the ticket as Can't Reproduce for now so it's not hanging in the backlog. In case we face the same issue in future, we will reopen the ticket.

**Closed by mbakholdina** 2021-04-15 10:06 UTC
Labels: Status: Can't Reproduce, Type: Bug, [core]
