### ISSUE TITLE
auto-reconnect mode issue

### ISSUE THREAD

**Issue by mks75** [Haivision/srt#693] opened 2019-05-17 21:29 UTC
Hi,
I have observed that during transport when losses occurs, both sender and receiver starts dropping packets, and after sometime (not always), the receiver disconnects srt source and closes the socket. After that it tries to re-connect with sender. However, the sender doesn't closes the socket and didn't try to establish the connection with the receiver. This result in no transfer of stream and neither sender nor receiver process terminates to indicate error. The only way to fix is to stop and start the sender process.
Here are the snapshots.
receiver:
![image](https://user-images.githubusercontent.com/34006918/57957044-00482b00-78c9-11e9-9d64-6c73b2a1c8bd.png)

sender:
![image](https://user-images.githubusercontent.com/34006918/57957063-0b9b5680-78c9-11e9-8b3b-0d95b500fb53.png)

thanks
mks

**Comment by maxlovic** [comment] 2019-05-22 11:49
@mks75 If you are using `srt-live-transmit` please specify the command line arguments used for both parties.

**Comment by mks75** [comment] 2019-05-28 17:28
Hi @maxlovic,
Following are the commands I am using.

(Sender):
./srt-live-transmit -s:1000 -a:yes "udp://@239.1.1.1:1234" "srt://xxx.xxx.xxx.xxx:xxxxx?mode=rendezvous&latency=1000"

(Receiver):
./srt-live-transmit -s:1000 -a:yes "srt://xxx.xxx.xxx.xxx:xxxxx?mode=rendezvous&latency=1000" "udp://@239.2.2.2:1234?ttl=64"

I have observed this issue couple of times - there is no stream transfer and both sender and receiver process keeps working and didn't terminate/exit.

Thanks
MKS

**Comment by maxlovic** [comment] 2019-05-29 08:45
@mks75 Hm, I wonder if that can be related to the rendezvous mode being used. Can you check the behavior with explicitly specified caller and listener?

**Comment by mks75** [comment] 2019-05-29 14:11
ok @maxlovic, I will setup a transfer in caller-listener mode and see if the error occurs.
I prefer rendezvous mode as in this case there is no need to open ports on firewall.

Thanks
MKS

**Comment by maxsharabayko** [comment] 2020-10-22 11:50
Hi @mks75 
> I will setup a transfer in caller-listener mode and see if the error occurs.

Did you have time to see if this issue also happens in caller/listener mode?

Might be related to #1255

**Comment by mks75** [comment] 2020-10-22 15:43
Hi @maxsharabayko , 
Yes, I have observed this in both rendezvous and caller-listener modes.
Thanks - MKS

**Comment by maxsharabayko** [comment] 2020-10-23 08:09
There is probably some data being accumulated on the input UDP socket while SRT destination is reconnecting.
Could you please collect CSV statistics (`-pf:csv -statsout:file.csv -stats:100`) and a network capture for analysis, if possible?

**Comment by mbakholdina** [comment] 2020-11-23 10:30
Hi @mks75,
Have you had a chance to collect SRT statistics and Wireshark dumps?

**Comment by mks75** [comment] 2020-12-01 17:26
Hi, This issue is intermittent and hard to replicate. Will update in case it occurs again.
Thanks- MKS

**Comment by mbakholdina** [comment] 2021-03-17 11:59
The issue isn't reproducible on our side. Closing the ticket. Please feel free to reopen it in case the problem appears again.

**Closed by mbakholdina** 2021-03-17 11:59 UTC
Labels: Priority: Low, Type: Bug, [apps]
