### ISSUE TITLE
[BUG] compiler note when cross-compiling with GCC 4.4 

### ISSUE THREAD

**Issue by jeandube** [Haivision/srt#2126] opened 2021-09-10 14:58 UTC
fork based on v1.4.4-rc.1
Compiler prints a note for many files  when cross-compiling for armv7l with GCC 4.4

/opt/CodeSourcery/Sourcery_G++_Lite/bin/arm-none-linux-gnueabi-g++   -DENABLE_MONOTONIC_CLOCK=1 -DENABLE_SOCK_CLOEXEC=1 -DFUGU_PLATFORM=1 -DHAI_ENABLE_SRT=1 -DHAI_PATCH=1 -DHAVE_INET_PTON=1 -DHAVE_PTHREAD_GETNAME_NP=1 -DHAVE_PTHREAD_SETNAME_NP=1 -DLINUX=1 -DSRT_DYNAMIC -DSRT_ENABLE_APP_READER -DSRT_ENABLE_BINDTODEVICE -DSRT_ENABLE_CLOSE_SYNCH -DSRT_ENABLE_ENCRYPTION -DSRT_ENABLE_THREADCHECK=1 -DSRT_EXPORTS -DSRT_VERSION=\"1.4.4\" -DUSE_OPENSSL=1 -D_GNU_SOURCE -DENABLE_LOGGING=1 -DENABLE_EXPERIMENTAL_BONDING=1 -Wall -Wextra -g -fPIC -I...snip/srt.git/common -I...snip/srtcore -I...snip/haicrypt -I...snip/srt.git -I/opt/CodeSourcery/Sourcery_G++_Lite/arm-none-linux-gnueabi/include    -I...snip/FUGU/../../components/include -o CMakeFiles/srt_virtual.dir/srtcore/group.cpp.o -c ...snip/srtcore/group.cpp
In file included from ...snip/srtcore/crypto.h:26,
                 from ...snip/srtcore/handshake.h:51,
                 from ...snip/srtcore/socketconfig.h:62,
                 from ...snip/srtcore/queue.h:58,
                 from ...snip/srtcore/api.h:63,
                 from ...snip/srtcore/group.cpp:5:
...snip/srtcore/logging.h:350: note: the mangling of 'va_list' has changed in GCC 4.4

This issue does not seem to affect the capability of the resulting lib to log.

**Comment by ethouris** [comment] 2021-09-10 16:30
The `-Wno-psabi` flag is said to hide this message. According to [this explanation](https://groups.google.com/g/android-ndk/c/mrk5dDqWioM) this warning only concerns cases when definition and usage are compiled using different compiler versions and therefore if you are compiling everything with the same version of the compiler, and the libraries use the same mangling (the matter of passing the elipsis arguments to `va_list` variable, and then this one to `vsprintf` call), there's nothing to worry about.

OTOH it would be worth considering removing the printf-formatting version of the logging instruction. It's almost not used at all in SRT as the "iostream style" version works fine.

**Comment by ethouris** [comment] 2021-09-21 15:55
Yes, surely that shouldn't be a regression. I found 36 occurrences of this so I really think getting rid of them could solve more problems.

**Comment by maxsharabayko** [comment] 2021-09-21 16:24
It might be also worth considering which one is faster: `LOGC` or `LOGF`.
`LOGF` (via `vsprintf`) does additional search and replace kind of things, so may have an inferior efficiency to `LOGC`. Therefore might be another point to get rid of it.

**Comment by ethouris** [comment] 2021-09-22 06:14
That's exactly my thinking.

**Comment by maxsharabayko** [comment] 2022-12-02 15:30
Hi @jeandube 
Could you please check it the issue persists in the latest master?

**Comment by ethouris** [comment] 2023-03-07 13:40
Closing because: LOGF/HLOGF have been deprecated and are not in use anywhere.

There's one case when `va_list` is still in use, it's in haicrypt logging, but this wasn't reported. Anyway, haicrypt logging is also turned off by default due to security reasons.

**Closed by ethouris** 2023-03-07 13:40 UTC
Labels: Type: Bug, [core], help wanted
