### ISSUE TITLE
stransmit does not work from 'dev' branch on windows

### ISSUE THREAD

**Issue by lewk2** [Haivision/srt#99] opened 2017-09-27 10:11 UTC
I've been setting up a test environment, with the focus on Windows compilation, and I have seen a few problems. With the master branch, I would get access violations on the receiver after some time (normally correlated to UDP packet loss). I have seen this with compilations of stransmit, and within my own test implementation of a receiver.

I decided to test with 'dev' branch, but I cannot (with same input arguments) get any data to flow. My test receiver seems to never step past srt_accept call when sending from stransmit.

Since I'm always unsure that the problem might not be my side, I have forked the repo and then connected up 'artefacts' from the build using the appveyor.yml file included (which I hope would rule out my local building issues, if they existed).

However, I still cannot get stransmit to work from 'dev' branch.

You can see builds here:

https://ci.appveyor.com/project/cinegy/srt/history

And fork here:

https://github.com/Cinegy/srt

Before diving in to try and work out what goes wrong - is this a known issue on Windows?

**Comment by heidabyr** [comment] 2017-09-27 10:18
Hi Lewis,

did you try the release version tagged as 1.2? We'll have a look at it!

- Marc

**Comment by lewk2** [comment] 2017-09-27 10:21
I poked it roughly... but now I have AppVeyor making clean compiles (and generating binaries) messing around with other builds is much easier.

Did you guys make a deliberate decision to not attach artefacts / binaries to your builds? It is a trivial pull request from me if you would like the change.

**Comment by lewk2** [comment] 2017-09-27 10:58
OK, I have tag 1.2.0 built now (even decided to experiment with the VS2013 compiled edition) and it works. However, after a few minutes this also excepted on my Win10 laptop (with SRT used over WiFi to make it work harder) wrapping a 2.5mbps stream.

So great - it works, but not so great - it does not run very long before it stops.

Anyway - since this bug is all about stransmit not working at all, I can confirm 1.2 and 'master' both work (with same input params) but 'dev' just hangs.

I shall open a different issue about SRT DLL / stranmaccess violations.

**Comment by ethouris** [comment] 2017-09-27 11:01
Sounds serious. Will you be able to roughly describe the reproduction procedure? I know, it's just sending a stream by stransmit, but some expectations about the time and conditions when it happens, parameters of the stream you are sending, as well as of the machines that are used for the test, will be very helpful.

**Comment by lewk2** [comment] 2017-09-27 11:22
Sure, I can probably actually set up a publically accessible temp VM inside AWS as a 'source' including a reasonably sensible looped TS input. I will rig this up, reproduce with this against my station, and then rig a receiver.

However, for now, here is what I have done:

1. Generate MPEGTS source (I'm using Cinegy Multiviewer as a source) with a unicast plain MPEGTS stream of 2mbps IBBBBP coded 30 GOP H264 in 960x540p25 with a 192Kbps MPEG audio stream. This is pointed at another machine being used as 'stransmitter'.
2. On transmit machine, this runs various 'stransmit' commands - currently, the argument looks like:
./stransmit -r:1000 udp://:1236 srt://10.186.6.104:9000

3. I have a couple of machines I try to receive on - most reliable crash comes when targeting my laptop over WiFi, which I use to echo the UDP back to multicast with this command:

./stransmit -r:1000 -s:1000 srt://:9000 udp://239.1.2.3:1234

I have messed around with varying use of 'tag 1.2' and 'master, and VS2013 release, VS2015 release and VS2015 debug.

My next step will be to use something other than my Win10 laptop as receiver.

**Comment by lewk2** [comment] 2017-09-27 11:23
Dammit, just realised I wrote up things about access violation in this thread.

Anyway - repeat all above, except instead of it failing after some time, you get no results at all when using dev (just hangs on receiver, and transmitter times out).

**Comment by lewk2** [comment] 2017-10-06 16:50
I have just checked this with the very latest DEV binaries - it seems to still be topical. Something is quite wrong with the receiving sockets in this branch. 

If I take DEV stransmit, and send to MASTER stransmit, I can see with Wireshark that a handshake is attempted (sender -> receiver), and I can see that handshake packets are returned (but ignored) by sender.

![image](https://user-images.githubusercontent.com/1837744/31288784-41f1cadc-aabe-11e7-9f86-fbe255d4d66d.png)

I suspect the socket is not opening / listening correcting in Windows - since if I now vary my setup substituting DEV stransmit on both ends; even with same arguments, packets are sent to receiver but there is no attempt to return the handshake in this case.

![image](https://user-images.githubusercontent.com/1837744/31288842-7fe371a6-aabe-11e7-823f-785712d98945.png)

I attach the exact command lines used in this screenshot:

![image](https://user-images.githubusercontent.com/1837744/31288899-c0a768d2-aabe-11e7-9cc3-768c71c2c949.png)

I have enough experience with the tool and the command line to feel confident this is not my error :-)

**Comment by ethouris** [comment] 2017-10-06 17:04
Ok, I'm not sure if I tested this on Windows, but at least I should be able to pick this up next and confront it with the logs. This version introduces the new handshake, but it also should recognize the version and fall back to the old rules if old version is detected. I'll see to it as soon as I can.

**Comment by ethouris** [comment] 2017-10-09 11:10
PR #124 should fix this problem. Actually this was a "portability violation" problem, nothing around the HSv5 handshake (that is, you'd see it also if both versions are new).

Please check and let me know.

BTW. if you'd like to play around with the Windows implementation of reading from socket - that is, provide the "proper way" of doing it (details are in the comments around the call to `WSARecvFrom`) - I will be grateful.

**Comment by ethouris** [comment] 2017-10-11 14:21
This should be merged now to `dev` branch, please check and close if ok.

**Comment by lewk2** [comment] 2017-10-12 19:15
Hello - sorry to be a bit slow. I'm afraid that while there is progress (it does not endlessly hang), it does not work either.

Please see a screenshot showing the exchange:

![image](https://user-images.githubusercontent.com/1837744/31514504-b70d6f0e-af89-11e7-836a-f466e9ed28ea.png)

I don't actually follow what the error here might be - it looks like something might be going wrong now at the protocol level.

Regarding getting some work done to the Windows socket layer - it is probably best I do not do anything myself, as I'm really not great with WinSock usage, but I could action one of our developers to do something. 

However, is it a good idea at this moment to do this, given the churn level that appears to be going on in the dev branch? Certainly working on another branch related against master would be possible, but it would probably make merging to dev a nightmare...

Would you expect the dev branch to settle a bit soon and be ready for just some WIN32 polishing? Or is this not realistic?

**Comment by ethouris** [comment] 2017-10-13 09:53
Thanks a lot for testing! You have actually proven that SRT works perfectly and exactly as expected.

This is a completely different kind of problem, and it's not even related to Windows (on Linux it fails exactly the same way). That's not even a problem in SRT - the problem is in `stransmit`; it should have been slightly readjusted to the payload size needs newly introduced in this version. I've created a new ticket to fix that, #130, and the whole problem is described there.

**Comment by ethouris** [comment] 2017-10-13 15:12
Ah, and referring to your other statements in the above comments:

The `dev` branch will simply **become** a new `master`, once the testing confirms its stability - there's nothing to worry about merging. Whatever bugfixes were added to `master` in the meantime, they should be in `dev`, too.

There will be definitely needed some activity for WIN32 polishing, we just need to achieve stability on `dev` branch and make it a release candidate. Probably changes like that can be added as minor version upgrade.

**Closed** 2017-11-16 13:59 UTC
Labels: Solution: Fixed, Status: Completed, Type: Bug
