### ISSUE TITLE
Date & Time stamp in Stats output

### ISSUE THREAD

**Issue by mks75** [Haivision/srt#685] opened 2019-05-10 17:00 UTC
Hi,
Is there a way to have Date and Time stamp in the stats parameter output?

Thanks
MKS

**Comment by maxlovic** [comment] 2019-05-27 12:16
Hi @mks75 
Sorry for the late reply.
Are you asking about this functionality in `srt-live-transmit`, or in the SRT library API?
SRT stats return the time since the UDT entity is started, in milliseconds `msTimeStamp`. And the time when you retrieve the stats, is the time for which this statistic is actual.

**Comment by mks75** [comment] 2019-05-28 16:52
Hi @maxlovic,
Yes, in the srt-live-transmit with -s option, the stats doesn't show local date and time, and if we are writing the stats to a log file and later analyzing its entries, we don't know when an error had happened.
for example, the following entry:
======= SRT STATS: sid=812246253
PACKETS     SENT:         996  RECEIVED:             0
LOST PKT    SENT:           0  RECEIVED:             0
REXMIT      SENT:           0  RECEIVED:             0
DROP PKT    SENT:           0  RECEIVED:             0
RATE     SENDING:     3.08249  RECEIVING:            0
BELATED RECEIVED:           0  AVG TIME:             0
REORDER DISTANCE:           0
WINDOW      FLOW:        7310  CONGESTION:        8192  FLIGHT:         115
LINK         RTT:   342.316ms  BANDWIDTH:    23.28Mb/s 
BUFFERLEFT:  SND:    12114000  RCV:           12286500
155288 bytes lost, 1531824 bytes sent, 1687112 bytes received


Although there are ways in Linux to add Date and time stamp while writing stats to log file, but I wonder if srt-live-transmit can output the same.

for example the following shows the workaround I am using:
Tue May 14 17:42:59 EDT 2019 ======= SRT STATS: sid=10162553
Tue May 14 17:42:59 EDT 2019 PACKETS     SENT:           0  RECEIVED:           999
Tue May 14 17:42:59 EDT 2019 LOST PKT    SENT:           0  RECEIVED:             0
Tue May 14 17:42:59 EDT 2019 REXMIT      SENT:           0  RECEIVED:             0
Tue May 14 17:42:59 EDT 2019 DROP PKT    SENT:           0  RECEIVED:             0
Tue May 14 17:42:59 EDT 2019 RATE     SENDING:           0  RECEIVING:      6.68503
Tue May 14 17:42:59 EDT 2019 BELATED RECEIVED:           0  AVG TIME:             0
Tue May 14 17:42:59 EDT 2019 REORDER DISTANCE:           0
Tue May 14 17:42:59 EDT 2019 WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
Tue May 14 17:42:59 EDT 2019 LINK         RTT:   243.971ms  BANDWIDTH:   96.384Mb/s
Tue May 14 17:42:59 EDT 2019 BUFFERLEFT:  SND:    12288000  RCV:            8617500


Thanks
MKS

**Comment by maxlovic** [comment] 2019-05-28 17:03
@mks75 Try `-pf:csv -statsout:stats.csv` .

**Comment by mks75** [comment] 2019-05-28 18:18
@maxlovic,
on ver 1.3.2, it says "ERROR: Unsupported print format: csv"
I guess this will work with the latest version of srt.
I am trying to compile the latest version, but seeing following message during "make".

[ 97%] Building CXX object CMakeFiles/srt-multiplex.dir/apps/srt-multiplex.cpp.o
/home/test/srt-master/apps/srt-multiplex.cpp: In member function ‘void MediumPair::TransmissionLoop()’:
/home/test/srt-master/apps/srt-multiplex.cpp:124:27: warning: unused variable ‘read_res’ [-Wunused-variable]
                 const int read_res = src->Read(chunk, data);
                           ^
[100%] Linking CXX executable srt-multiplex
[100%] Built target srt-multiplex

Please advise.

Thanks
MKS

**Comment by maxlovic** [comment] 2019-05-29 07:49
It is just a warning, so `srt-live-transmit` should be built. Warning will be fixed in an upcomming PR.

**Comment by mks75** [comment] 2019-05-29 14:06
@maxlovic,
Are there any changes in this version of srt-live-transmit, as it's giving error when using : sign.
-pf:csv -statsout:stats.csv

Thanks
MKS

**Comment by maxlovic** [comment] 2019-05-29 15:02
@mks75 What kind of error and which version of `srt-live-transmit`?
I tried e.g. this command:
`srt-live-transmit file://con srt://:4200 -s:1000 -statsout:file.csv -pf:csv`

**Comment by mks75** [comment] 2019-05-29 15:15
@maxlovic,
I am using the latest master, and I am seeing the following error.
**ERROR. Invalid syntax. Specify source and target URIs.**

my command at sender side is:
./srt-live-transmit -s:1000 -pf:json -statsout:stats.json "udp://@239.1.1.1:1234" "srt://xxx.xxx.xxx.xxx:xxxxx?mode=rendezvous&latency=1000"

I didn't see any such error with ver 1.3.2

Thanks
MKS

**Comment by brucedk** [comment] 2019-05-29 18:21
Guys, I don't know if it is the same problem, but here in my work, I had some issues on 1.3.3 using ":" in some scripts and bat files. They always need to be in UTF-8 to work properly. I'm using win10

**Comment by maxlovic** [comment] 2019-05-29 19:00
@mks75 @brucedk There appeared to be an issue with argument parsing. @ethouris has found the problem, it will be fixed. Meanwhile place SRC and DST in the beginning, like:
`./srt-live-transmit "udp://@239.1.1.1:1234" "srt://xxx.xxx.xxx.xxx:xxxxx?mode=rendezvous&latency=1000" -s:1000 -pf:json -statsout:stats.json`

**Comment by mks75** [comment] 2019-05-30 13:04
Hi @maxlovic,
The csv file also don't have local date and time. Date and time reference in the log file helps to understand as when an issue has occurred over a period of time.
How we can include local date and time in the csv log entries? Please advise.

sample snapshot:
10583,703163698,8192,8192,0,247.395,61.44,30,0,0,0,0,0,0,0,362,1001,0,0,0,0,1361360,0,0,8.96086,4000
11799,703163698,8192,8192,0,247.549,83.508,30,0,0,0,0,0,0,0,362,1005,0,0,0,0,1366800,0,0,8.98718,4000
13024,703163698,8192,8192,0,247.546,55.416,30,0,0,0,0,0,0,0,362,1002,0,0,0,0,1362720,0,0,8.9038,4000
14231,703163698,8192,8192,0,247.107,78.204,30,0,0,0,0,0,0,0,362,997,0,0,0,0,1355920,0,0,8.98698,4000
15447,703163698,8192,8192,0,247.171,124.428,30,0,0,0,0,0,0,0,362,995,0,0,0,0,1353200,0,0,8.90212,4000
16672,703163698,8192,8192,0,247.397,72.948,30,0,0,0,0,0,0,0,362,1007,0,0,0,0,1369520,0,0,8.94503,4000
17886,703163698,8192,8192,0,247.676,49.044,30,0,0,0,0,0,0,0,362,1001,0,0,0,0,1361360,0,0,8.96844,4000
19106,703163698,8192,8192,0,247.285,125.304,30,0,0,0,0,0,0,0,362,1000,0,0,0,0,1360000,0,0,8.92205,4000
20318,703163698,8192,8192,0,247.518,111.348,30,0,0,0,0,0,0,0,362,999,0,0,0,0,1358640,0,0,8.96453,4000

Thanks
MKS

**Comment by maxlovic** [comment] 2019-05-30 14:12
Hi @mks75 
Output of the statistics is performed [here](https://github.com/Haivision/srt/blob/master/apps/transmitmedia.cpp#L150). So just add one column to print a timestamp to CSV.

For example, the following function will format a timestamp:
```
std::string print_time()
{
    time_t time = chrono::system_clock::to_time_t(std::chrono::system_clock::now());
    tm *tm = localtime(&time);
    time_t usec = time % 1000000;

    char tmp_buf[512];
#ifdef _WIN32
    strftime(tmp_buf, 512, "%T.", tm);
#else
    strftime(tmp_buf, 512, "%T.", tm);
#endif
    ostringstream out;
    out << tmp_buf << setfill('0') << setw(6) << usec << " ";
    return out.str();
}
```

**Comment by mks75** [comment] 2019-05-30 16:27
@maxlovic,
I tried to add this function at the end of srt/apps/transmitmedia.cpp file and at l154 added print_time (output << "print_time,Time,SocketID,pktFlowWindow,pktCongestionWindow,pktFlightSize,";), but getting several errors during make. I am not good at this and doing something wrong here.
Could you please include this function and provide the complete transmitmedia.cpp

snapshot during make:
[ 73%] Building CXX object CMakeFiles/srtsupport_virtual.dir/apps/transmitmedia.cpp.o
/home/test/srt-dev-v133/srt/apps/transmitmedia.cpp: In function ?std::__cxx11::string print_time()?:
/home/test/srt-dev-v133/srt/apps/transmitmedia.cpp:1221:19: error: ?chrono? has not been declared
     time_t time = chrono::system_clock::to_time_t(std::chrono::system_clock::now());
                   ^
/home/test/srt-dev-v133/srt/apps/transmitmedia.cpp:1221:56: error: ?std::chrono? has not been declared
     time_t time = chrono::system_clock::to_time_t(std::chrono::system_clock::now());
                                                        ^
CMakeFiles/srtsupport_virtual.dir/build.make:110: recipe for target 'CMakeFiles/srtsupport_virtual.dir/apps/transmitmedia.cpp.o' failed
make[2]: *** [CMakeFiles/srtsupport_virtual.dir/apps/transmitmedia.cpp.o] Error 1
CMakeFiles/Makefile2:255: recipe for target 'CMakeFiles/srtsupport_virtual.dir/all' failed
make[1]: *** [CMakeFiles/srtsupport_virtual.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Thanks
MKS

**Comment by ethouris** [comment] 2019-05-31 12:28
@mks75 
Your previous comment: you need to `#include <chrono>` to compile this - and mind that this example function formats the current time (`now`), not given time. If this still won't compile, it may be a compiler problem (found that already with MinGW).

As for your problem with the command line - you found a bug. #714 is going to address the problem, bugfix is underway. The problem is that the option with colon even though it already has an argument, it still eats one argument from the command line. You can work it around by passing "free arguments" first and options next.

**Comment by mks75** [comment] 2019-05-31 15:31
Thanks @maxlovic,
I am able to compile it now, and I am seeing the time in csv.
Is there a way to add Date as well, because after 24 hrs we don't know which day it was?

snapshot:
13:41:37.238097 ,32492,983808178,8192,8192,0,245.156,55.008,30,0,0,0,0,0,0,0,362,997,1,0,2,1,1355920,1360,0,8.94029,4000
13:41:39.238099 ,33713,983808178,8192,8192,0,246.402,57.12,30,0,0,0,0,0,0,0,362,995,2,0,0,0,1353200,2720,0,8.86798,4000
13:41:40.238100 ,34925,983808178,8192,8192,0,245.514,46.752,30,0,0,0,0,0,0,0,362,1013,2,0,8,4,1377680,2720,0,9.09099,4000
13:41:41.238101 ,36144,983808178,8192,8192,0,245.07,103.872,30,0,0,0,0,0,0,0,362,1001,0,0,0,0,1361360,0,0,8.93768,4000
13:41:42.238102 ,37361,983808178,8192,8192,0,244.493,717.672,30,0,0,0,0,0,0,0,362,995,0,0,0,0,1353200,0,0,8.89437,4000
13:41:44.238104 ,38582,983808178,8192,8192,0,244.92,102.888,30,0,0,0,0,0,0,0,362,1005,0,0,0,0,1366800,0,0,8.95237,4000
13:41:45.238105 ,39791,983808178,8192,8192,0,245.113,49.404,30,0,0,0,0,0,0,0,362,995,3,0,2,1,1353200,4080,0,8.9553,4000
13:41:46.238106 ,41009,983808178,8192,8192,0,244.747,56.532,30,0,0,0,0,0,0,0,362,1007,0,0,4,2,1369520,0,0,8.99622,4000

Thanks
MKS

**Comment by maxlovic** [comment] 2019-06-24 05:07
Hi @mks75 
Please refer to [`strftime`](http://www.cplusplus.com/reference/ctime/strftime/) docs.
For example, you could use `strftime(tmp_buf, 512, "%F %T", tm);`

**Closed** 2019-07-23 10:43 UTC
Labels: Status: Completed, Type: Question, [apps]
