### ISSUE TITLE
srt-live-transmit - strange behaviour with jitter

### ISSUE THREAD

**Issue by deraltehund** [Haivision/srt#735] opened 2019-06-13 12:19 UTC
Hi there,
I recently tested srt-live-transmit under simulated network disturbances. I did this using traffic control/netem on Ubuntu 18.04.2/4.18.0-21, SRT Version 1.3.2 and noticed that just a little artificial jitter causes SRT to misbehave.

I was using a consumer grade internet connection with good performance: 40 mpbs upload, jitter avg. 4ms (0-34ms), ping avg. 25 ms (20-59ms), no packet loss. SRT runs fine on this line, adding roughly 5-10% overhead to encoded video. Measuring the simulated disturbances with nperf I did not see any irregularities. Values seem to rise in accordance to what I adjust. And still no packet loss.

BUT - introducing only 1ms of jitter (for instance: tc qdisc change dev eno2 root netem delay 50ms 1ms) will raise the outgoing datarate about 70%. In the logs I can see that about 4000 of 9000 packets have to be retransmitted. Going higher (delay 100ms jitter 30ms) the datarate reaches more than twice the original value and roughly every 2nd packet is retransmitted.

Adding packet loss is much more predictable and acting linearly. Also, delay without jitter does not do any harm.. so this seems to be a special case.

I guess this is not significant for "real world" network scenarios, nevertheless I'd like to have an explanation for that or hear if anybody else can confirm this issue.

SRT command looks like this: ./srt-live-transmit -loglevel:note -v -r:5000 -s:5000 "file://con" "srt://X.X.X.X:3196?inputbw=9000000&oheadbw=40&pkt_size=1316&transtype=live&latency=4000&mode=caller"

THANKS!

**Comment by maxlovic** [comment] 2019-07-01 10:26
Hi @deraltehund 
This looks related to packet reordering. By default a receiver triggers loss report on any gaps in packets sequence numbers.
Please check `SRTO_LOSSMAXTTL` option to set maximum reorder tolerance (URI query `lossmaxttl`). Refer to `SRTO_LOSSMAXTTL` in [API.md](https://github.com/Haivision/srt/blob/master/docs/API.md).

**Comment by maxlovic** [comment] 2019-07-15 11:24
Hi @deraltehund 
Please share an update on this.

**Comment by deraltehund** [comment] 2019-07-16 09:08
Hello @maxlovic 
Finally, I did another test, going like this, also reducing `oheadbw`:
`./srt-live-transmit -loglevel:note -v -r:5000 -s:5000 "file://con" "srt://X.X.X.X:XXXX?inputbw=8000000&oheadbw=10&pkt_size=1316&transtype=live&latency=2000&mode=caller&lossmaxttl=10000"`

Unfortunately, again this
`sudo tc qdisc add dev eno2 root netem delay 20ms 1ms`
is enough to mess it up and results in the log below. The bitrate now 14 instead of 8 Mb/s is actually going out. Interestingly it measures the link/SRT bandwidth now with 2.7 Mb/s which was before 30 Mb/s.

+++/+++SRT BANDWIDTH: 2.7
======= SRT STATS: sid=928462013
PACKETS     SENT:        8305  RECEIVED:             0
LOST PKT    SENT:        3461  RECEIVED:             0
REXMIT      SENT:        3306  RECEIVED:             0
DROP PKT    SENT:           0  RECEIVED:             0
RATE     SENDING:     14.0347  RECEIVING:            0
BELATED RECEIVED:           0  AVG TIME:             0
REORDER DISTANCE:           0
WINDOW      FLOW:        6322  CONGESTION:        8192  FLIGHT:          31
LINK         RTT:     44.87ms  BANDWIDTH:      2.7Mb/s 
BUFFERLEFT:  SND:    12240000  RCV:           12286500

**Comment by maxlovic** [comment] 2019-07-16 10:56
What do you use as a source of data?

**Comment by deraltehund** [comment] 2019-07-16 11:02
this is an ffmpeg encoding piping an mpegts..

**Comment by maxlovic** [comment] 2019-07-16 11:06
Looks like we will have to reproduce it to understand what is going on.
@ethouris any ideas?

**Comment by jeandube** [comment] 2019-07-16 11:54
netem jitter actually introduces packet reordering, which is detected a lost packets by SRT.

**Comment by maxlovic** [comment] 2019-07-16 12:00
@jeandube Setting the `SRTO_LOSSMAXTTL` to 10000 didn't help. And the stats show `REORDER DISTANCE: 0`

**Comment by maxlovic** [comment] 2019-07-16 16:15
Might this be related to #753?

**Comment by ethouris** [comment] 2019-08-06 16:05
@jeandube : `netem delay` does not introduce reordering. For reordering you have a dedicated `reorder` option.

According to the documentation, `netem delay Dms Jms` introduces delay to EVERY packet passing the iface which counts D +-J. So in this case above it introduces a delay on a packet that varies randomly from 19ms to 21ms - if I understand the "delay and jitter" terms correctly.

If you want to do reordering, there's an additional `reorder` option that should be used together with `delay`. This option causes that this delay only apply to some range of packets, whereas other packets be sent without a delay, with some defined probability and variance.

So `SRTO_LOSSMAXTTL` won't help you here.

Note also that a reasonable value for `SRTO_LOSSMAXTTL` is 10. This option defines a MAXIMUM (not "always applying") number of packets to be received first after seeing an alleged loss so that this loss can be reported ("reorder tolerance"). The "reorder tolerance" starts from 0 and it grows upon detection of the first "reordered" packet (packet that has a "belated" sequence but no R flag set) to the value being a "belated distance". The value for `SRTO_LOSSMAXTTL` is the highest value up to which this reorder tolerance can grow during reorder detection.

In order to detect what really happened here I'd rather calculate the distance between two packets at the current rate compared with the delay applied, and check the stats - flight window first of all - in both normal and impaired conditions. These stats above don't look bad, however hard to say anything certain about them without confronting them with the receiver stats.

@deraltehund I also need the **exact ffmpeg command** you used for this test.

**Comment by deraltehund** [comment] 2019-08-15 09:31
Hi there,
finally I find some time.. Here you go with the ffmpeg cmd:
`./ffmpeg -y -loglevel info -stream_loop 300 -re -i ~/test/123_720p25.mp4 -r 25 -c:v h264 -vf "scale=1920x1080" -pix_fmt yuv420p -g 50 -keyint_min 50 -x264-params scenecut=0:b-adapt=0:bframes=2:b-pyramid=none:open-gop=0:ref=2:mixed-refs=0:rc-lookahead=50 -b:v 8000k -maxrate 8000k -minrate 8000k -bufsize 8000k -profile:v high -level 4.1 -preset medium -c:a aac -b:a 320k -ar 48000 -f mpegts - | ./srt-live-transmit -loglevel:note -v -r:5000 -s:5000 "file://con" "srt://x.x.x.x:3178?inputbw=8000000&oheadbw=40&pkt_size=1316&transtype=live&latency=4000&mode=caller" 2> ~/test/srt-log_190815.txt`

then add:
`tc qdisc add dev eno1 root netem delay 50ms 1ms`

resulting in:
PACKETS     SENT:        8607  RECEIVED:             0
LOST PKT    SENT:        3913  RECEIVED:             0
REXMIT      SENT:        3577  RECEIVED:             0
DROP PKT    SENT:           0  RECEIVED:             0
RATE     SENDING:     13.8934  RECEIVING:            0
BELATED RECEIVED:           0  AVG TIME:             0
REORDER DISTANCE:           0
WINDOW      FLOW:        5201  CONGESTION:        8192  FLIGHT:         131
LINK         RTT:      71.6ms  BANDWIDTH:    2.988Mb/s 
BUFFERLEFT:  SND:    12121500  RCV:           12286500

**Comment by ethouris** [comment] 2019-08-15 10:30
I think I miss something here, but just after quick take-a-look:

How come that you have 50% packet loss? Unlikely that the impairment implied by this `tc` command has caused it. Moreover, you have a measured available bandwidth shown as ~3Mb/s, how could then an 8Mb/s stream get passthru? Even if the bandwidth measurement somehow isn't accurate, it definitely cannot be below the input rate, if your link can withstand it.

**Comment by maxlovic** [comment] 2019-08-15 11:05
@deraltehund Please also attach CSV statistics, so that we can see the dynamics.
```
./srt-live-transmit -loglevel:note -v -s:5000 -pf:csv -statsout:stats-snd.csv
"file://con" "srt://x.x.x.x:3178?inputbw=8000000&oheadbw=40&pkt_size=1316
&transtype=live&latency=4000&mode=caller"
```

**Comment by deraltehund** [comment] 2019-08-15 11:05
Hi there,
please see my above post from July, 16th. The link bandwidth is being measured wrongly.
Before inserting traffic control the stats look like
PACKETS     SENT:        4932  RECEIVED:             0
LOST PKT    SENT:           0  RECEIVED:             0
REXMIT      SENT:           0  RECEIVED:             0
DROP PKT    SENT:           0  RECEIVED:             0
RATE     SENDING:     9.28201  RECEIVING:            0
BELATED RECEIVED:           0  AVG TIME:             0
REORDER DISTANCE:           0
WINDOW      FLOW:        4934  CONGESTION:        8192  FLIGHT:          77
LINK         RTT:    20.784ms  BANDWIDTH:   69.648Mb/s 
BUFFERLEFT:  SND:    12042000  RCV:           12286500

The link is actually a 50mbps upload line. The stream of 8mbps is passing through flawlessly, although srt transmit measures these 3mbps.

**Comment by deraltehund** [comment] 2019-08-15 11:13
unfortunately it does not want to print out the CSV "ERROR: Unsupported print format: csv"

**Comment by maxlovic** [comment] 2019-08-15 21:12
Which version are you using? CSV appeared in 1.3.3.

**Comment by deraltehund** [comment] 2019-08-19 11:03
Hi there.. well, now it's 1.3.3 :) 
(was 1.3.2)
Attached the CSV file. As you can see at time 146078 the traffic control kicks in.
[stats-snd.zip](https://github.com/Haivision/srt/files/3515500/stats-snd.zip)

**Comment by maxlovic** [comment] 2019-08-19 11:39
Packet retransmission if triggered after RTT is increased.
Could you please also collect debug logs at least on the sender's side?
Build with `-DENABLE_HEAVY_LOGGING=ON`
Run with `-loglevel debug`.

![stats-snd-packets](https://user-images.githubusercontent.com/12700120/63261984-188f6380-c285-11e9-82b5-b682237f9d6f.png)

![stats-snd-rate](https://user-images.githubusercontent.com/12700120/63261992-1cbb8100-c285-11e9-9d2a-1a7660bd2142.png)

![stats-snd-rtt](https://user-images.githubusercontent.com/12700120/63261997-1fb67180-c285-11e9-9c3b-5dfcbcf16d96.png)

**Comment by deraltehund** [comment] 2019-08-19 14:48
RTT/delay alone does not do any harm! Of course both have been activated the same tame but the issue is only about jitter..
Here you go with the log:
[srt-log_190819.zip](https://github.com/Haivision/srt/files/3516393/srt-log_190819.zip)

**Comment by maxlovic** [comment] 2019-08-19 15:08
Quick look, and it is receiver who sends loss reports. Not a decision of the sender.
Could you collect the same logs for the receiver?

**Comment by deraltehund** [comment] 2019-08-19 16:21
ok.. this will have to wait until Wednesday. I´ll keep you posted!

**Comment by deraltehund** [comment] 2019-08-28 11:48
[srt-rec_DEBUG.zip](https://github.com/Haivision/srt/files/3550663/srt-rec_DEBUG.zip)

here you go with a receiver log - this has been transmitted over local network. Packet retransmission as formerly described..

**Comment by maxlovic** [comment] 2019-08-28 12:21
I see belated packets in the log. And looks like you do not turn on the reordering tolerance (SRTO_LOSSMAXTTL). Can you check this please?
There are belated packets even by 25 sequence numbers.

**Comment by deraltehund** [comment] 2019-08-28 17:39
Hi,
I set lossmaxttl=10. Packet retransmission as usual.
See log below. Thanks!
[srt-rec_DEBUG3.zip](https://github.com/Haivision/srt/files/3552172/srt-rec_DEBUG3.zip)

**Comment by maxlovic** [comment] 2019-08-29 09:32
Hi, @deraltehund 
Weird, but it still looks like the reorder tolerance is not set. Could you please share your command line to run the test?

### TODO
- [ ] Add traceReorderDistance to CSV stats output

**Comment by deraltehund** [comment] 2019-08-29 11:50
Sure, I think it went like this:
`| ./srt-live-transmit -loglevel:info -v -r:5000 -s:5000 -pf:csv -statsout:fflog/stats-snd.csv "file://con" "srt://192.168.2.122:5555?mode=caller&inputbw=8000000&oheadbw=40&pkt_size=1316&transtype=live&latency=2000&lossmaxttl=10" 2> fflog/srt-log_190828.txt \
`

**Comment by maxlovic** [comment] 2019-08-29 13:22
This option must be set on the receiver. Looks like you are setting it on the sender.

**Comment by deraltehund** [comment] 2019-08-29 14:13
ok that´s true. Will do and report back.

**Comment by deraltehund** [comment] 2019-09-02 07:38
Good morning!
So I was running this on the receiver:
`./srt-live-transmit-heavy-log -loglevel:debug -pf:csv -statsout:~/bin/fflog-rec/stats-rcv.csv "srt://:5555?mode=listener&lossmaxttl=10000" "file://con" 2> ~/bin/fflog-rec/srt-rec_DEBUG3.txt`
Behaviour still the same, see
[srt-rec_DEBUG_rcv.zip](https://github.com/Haivision/srt/files/3564931/srt-rec_DEBUG_rcv.zip)

**Comment by maxlovic** [comment] 2019-09-02 09:32
Hi @deraltehund. That turned to be a bug. The reorder tolerance setting is not transferred to the accepted socket. Working on a fix.

**Closed** 2019-09-03 16:10 UTC
Labels: Priority: High, Type: Bug, [core]
