### ISSUE TITLE
1.3.1 release fails to build in Windows VS2017

### ISSUE THREAD

**Issue by Svyatk0** [Haivision/srt#451] opened 2018-08-23 09:26 UTC
Hi guys. 
Has anything changed in build process for Windows between version 1.3.0 and 1.3.1 (latest master)? 

Running 2 builds side by side, same directory structure, pthread, openssl libs, Cmake configuration etc. and I am succeeding in building 1.3.0 and failing miserably building 1.3.1 version with  700+ Errors and 300+ warnings. Ranging from dll linking errors to all sorts of syntax errors. Dont even know where to start fixing this. 

Did anyone try building latest release in VS2017 for Winx64 ? 

Thanks

**Comment by ethouris** [comment] 2018-08-23 09:53
We can start with getting the list of these errors. Might happen that there's something simple in the project settings.

**Comment by ethouris** [comment] 2018-08-23 11:17
That's pretty weird with the `srt.pc` file. Although it plays no role in the compiling process on Windows, the contents in **Requires.private** should be filled by the result of `SRT_LIBS_PRIVATE` variable in cmake, which again should be filled by the values of `SSL_LIBRARIES` and `ws2_32.lib`. The value of `SSL_LIBRARIES` is displayed also in the cmake output and it looks extremely weird - it's not a list of libraries, it's a kinda dictionary, and for that the cmake script doesn't seem to be prepared.

I can see that most of the errors come from stdint.h - we have a nonstandard header for it as we need the definitions provided there, unfortunately they are provided as part of C99 and later C++11, but they are not available OOTB in C++98, the standard that we use for the project. These definitions are provided nicely by all POSIX compilers (although in this case it should be treated as a nonstandard extension), but not on all windows compilers. The provided `stdint.h` file (I suspect it is dated to the original UDT) contains some definitions that it relies on being provided by the compiler (`_C_STD_BEGIN` etc), which need not be true everywhere.

I guess this could be fixed by adding some conditionals that would detect the version of the compiler and when it's any compiler that provides headers for `inttypes.h` and `stdint.h`, the standard ones should be used.

There area also "manual" definitions for it around line 42 in `srt.h` - those probably should be also at least excluded in case of this compiler.

To my best knowledge, you should be able to recognize the `#include` instruction that uses them by `win/` path prefix. There's an include path added to `common` directory, but there should be nothing there now beside this `win` directory, but I think there's nothing leading directly to this `win` directory (otherwise we'd have a problem with eclipsing the system header by private header, which I believe isn't the case).

**Comment by Svyatk0** [comment] 2018-08-23 11:43
Going through files with difmerge in both BUILD directories, i also found that in 1.3.1 **C:\SRT\srt-master\BUILD\cmake_install.cmake** last few lines with the `common` path are missing. Which is what you have mentioned above (i think) 

> if("x${CMAKE_INSTALL_COMPONENT}x"
 STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/srt" TYPE FILE FILES
    "C:/SRT/srt-master/BUILD/version.h"
    "C:/SRT/srt-master/srtcore/srt.h"
    "C:/SRT/srt-master/srtcore/logging_api.h"
    "C:/SRT/srt-master/srtcore/platform_sys.h"
    "C:/SRT/srt-master/srtcore/udt.h"
    "C:/SRT/srt-master/srtcore/srt4udt.h"
    **"C:/SRT/srt-master/common/win/syslog_defs.h"
    "C:/SRT/srt-master/common/win/inttypes.h"
    "C:/SRT/srt-master/common/win/stdint.h"
    "C:/SRT/srt-master/common/win/unistd.h"**

will try to see what else is there, but as it currently stands there is no building in Windows.

**Comment by ethouris** [comment] 2018-08-23 15:41
Please find this line in CMakeLists.txt

`	message(STATUS "WINDOWS detected: adding compat sources: ${SOURCES_common}")`

and add displaying of `HEADERS_srt_win32` variable. These file should be extracted from the filelist and then requested installation from this instruction:

    if (WIN32)
	    install(FILES ${HEADERS_srt_win32} DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/srt/win)
    endif()

Although I suspect a problem due to the fact that this list is added to `HEADERS_srt`. Whatever, you can add also a "message" to the instruction above to see if these files are really added to installation.

**Comment by Svyatk0** [comment] 2018-08-24 09:36
Nice one, you nailed it :-) 
Other than few warning everything builds without issues. In case of interest, I am attaching the warnings log. 
[srt_1.3.1_warnings.txt](https://github.com/Haivision/srt/files/2317811/srt_1.3.1_warnings.txt)

Thanks again, this can probably be closed.

**Comment by ethouris** [comment] 2018-08-27 07:01
Well, but I actually didn't fix anything :). The only thing I said was to display the variable to know what's going on and where the problem may be.

The only explanation that this fixed the problem is that your real problem was that you didn't start with a clean build. Would you be able to check this, just to be sure?

**Comment by Svyatk0** [comment] 2018-08-28 10:07
Hiya. 
I can confirm I was starting clean for each build for the SRT build. What I didn't build from scratch was OpenSSL and Pthreads. These were built as a separate project at the time of initial 1.3.0 compiles. 
Also, CMake and VS2017 install was from earlier projects, which shouldn't make a difference :-)

**Comment by ethouris** [comment] 2018-08-29 14:05
Sorry, I'm confused now. Is the problem gone - somehow - or do we need a fix?

**Comment by Svyatk0** [comment] 2018-08-29 14:32
apologies for the confusion. I understood that you needed confirmation on whether i was doing clean builds or not at the time when i was seeing all the errors, so i have answered above. 

I have managed to get a successful build after your suggested addition to CMakeLists.txt

Thanks

**Closed** 2018-09-07 11:59 UTC
