### ISSUE TITLE
High CPU usage in Rendezvous mode V140

### ISSUE THREAD

**Issue by mks75** [Haivision/srt#906] opened 2019-10-13 23:06 UTC
Hi,
In v140, I have observed high cpu usage while using rendezvous mode. It shows around 107% on the Tx side and 25% on the Rx side. 
Please see the cpu usage snapshot on the Tx side. It utilizes single core up to 100%.  

![image](https://user-images.githubusercontent.com/34006918/66723547-3641fa80-ede8-11e9-8005-0991ae90e50b.png)

Also, in this mode, under statistics the reported bandwidth for the path is incorrect (showing very less available bandwidth).

The corresponding parameters reg CPU usage and bandwidth stats are ok in client-server mode.

Thanks
MKS

**Comment by stoyanovgeorge** [comment] 2019-10-18 12:51
I can also confirm that in v.1.40 the CPU usage in caller mode is also fully occupied with a single stream. I am receiving a 1080i50@18Mbps UDP stream and sending out an SRT stream.

**Comment by maxlovic** [comment] 2019-10-18 13:23
Could you please find a commit that introduces the issue, or at least narrow down the range of commits? This would be of a great help!

**Comment by colmaengus** [comment] 2019-10-22 13:08
The CPU usage jumped in https://github.com/Haivision/srt/commit/e59a8bda6b630dec98b8e0437d0906d9e5cbdd98

**Comment by maxlovic** [comment] 2019-10-22 14:51
@colmaengus Thanks for checking!
Putting related issues for further reference: #893, #906, #669.

**Comment by maxlovic** [comment] 2019-10-22 14:56
@colmaengus @stoyanovgeorge Which OS do you use for tests?

**Comment by colmaengus** [comment] 2019-10-22 19:58
I'm using ubuntu 18.04 in a docker (see #893 for details).
Build is done using cmake -B/usr/src/srt/build -H/usr/src/srt; make -C /usr/src/srt/build

**Comment by mks75** [comment] 2019-10-22 23:37
Hi, I am using Ubuntu 16.04 LTS.

Thanks
MKS

**Comment by stoyanovgeorge** [comment] 2019-10-25 13:10
I am using Ubuntu 19.10.

**Comment by stoyanovgeorge** [comment] 2019-10-25 13:10
> @colmaengus @stoyanovgeorge Which OS do you use for tests?

Ubuntu 19.10 for me.

**Comment by ethouris** [comment] 2019-10-25 14:24
There's a fix in #919. The problem with the reimplemented epoll was that the function doing `update_usock` did not properly remove events that the user wanted to unsubscribe from SIMULTANEOUSLY. With this bug, definitely this call below in `srt-live-transmit`:
```
                                const int events = SRT_EPOLL_IN | SRT_EPOLL_ERR;
                                // Disable OUT event polling when connected
                                if (srt_epoll_update_usock(pollid,
                                    tar->GetSRTSocket(), &events))
                                {
```

actually didn't disable OUT event, and then every next call to `srt_epoll_wait` was exitting always immediately (due to readiness for writing), making this exit spurious according to expectations. This definitely made it spin-looping.

If you can, please check the following:
 - on the receiver side, try to use `srt-test-live` instead of `srt-live-transmit` (you need to build with `--enable-testing`/`-DENABLE_TESTING=1`) . It works more-less the same way, just it's less user-friendly (exits when connection is broken). This problem should not occur there
 - there is a fix in #919, you might want to check on this branch if this fixes the problem

**Comment by maxlovic** [comment] 2019-10-29 09:24
@stoyanovgeorge @mks75 @colmaengus Could you please check if PR #919 solves this issue?

**Comment by colmaengus** [comment] 2019-10-29 16:34
I can confirm that #919 fixes the high CPU issue seen in my test setup.

**Comment by maxlovic** [comment] 2019-11-01 11:19
PR #919 is now merged to the master. Closing.
Thank you for reporting and checking!

**Closed by maxlovic** 2019-11-01 11:19 UTC
Labels: Status: Pending, Type: Bug, [core]
