### ISSUE TITLE
[BUG] Statistics always return instantaneous value for send and recv buffers

### ISSUE THREAD

**Issue by fboucher67** [Haivision/srt#1272] opened 2020-05-07 17:32 UTC
Calling srt_bstats or srt_bistats with instantaneous equal to 0 return instantaneous values for msRcvBuf and msSndBuf rather than moving averages as documented by statistics.md

A moving average value is reported when the value is retrieved by calling `srt_bstats(...)` or `srt_bistats(SRTSOCKET u, SRT_TRACEBSTATS * perf, int clear, int instantaneous)` with instantaneous=false`.

When calculating a moving average, it should be calculated using previous average value and a new sample.  The code in buffer.cpp does calculation of average using only the new sample so it is a instantaneous measurement rather than an average.

**Comment by mbakholdina** [comment] 2020-05-13 16:10
Hi @fboucher67, thank you for reporting the issue!

I confirm it's an error in the implementation. In `buffer.cpp`, function `void CRcvBuffer::updRcvAvgDataSize(const steady_clock::time_point& now)`, there is a code block
```
m_iCountMAvg      = (int)(((count * (1000 - elapsed_ms)) + (count      * elapsed_ms)) / 1000);
m_iBytesCountMAvg = (int)(((bytescount * (1000 - elapsed_ms)) + (bytescount * elapsed_ms)) / 1000);
m_TimespanMAvg    = (int)(((instspan * (1000 - elapsed_ms)) + (instspan   * elapsed_ms)) / 1000);
```
which should be fixed as follows
```
m_iCountMAvg      = (int)(((m_iCountMAvg * (1000 - elapsed_ms)) + (count      * elapsed_ms)) / 1000);
m_iBytesCountMAvg = (int)(((m_iBytesCountMAvg * (1000 - elapsed_ms)) + (bytescount * elapsed_ms)) / 1000);
m_TimespanMAvg    = (int)(((m_TimespanMAvg * (1000 - elapsed_ms)) + (instspan   * elapsed_ms)) / 1000);
```

**Comment by maxsharabayko** [comment] 2020-05-27 08:55
@fboucher67 Thanks for reporting. The issue is now fixed in the master branch.

**Comment by mbakholdina** [comment] 2020-06-09 08:14
@maxsharabayko The value of `msSndBuf` has not been fixed, reopening.

**Closed** 2020-06-17 09:25 UTC
Labels: Type: Bug, [core]
