### ISSUE TITLE
Send speed drops after 1 hour

### ISSUE THREAD

**Issue by Gummilion** [Haivision/srt#291] opened 2018-03-02 10:26 UTC
Hello.
I faced strange issue with srt library on our iPhone project.
After one hour of transmission (~62 minutes) srt_sendmsg actually slows down to only 60 packets (77 KB) per second (I can see it in Xcode network report) and report errors like `SRT.d: SND-DROPPED 4 packets - lost delaying for 2031ms` continually. I have checked several times - it always start after same interval and doesn't depend on amount of data. When I tries to call srt_close after that from another thread it stuck inside. For shorter sessions it sends 5 mbit/s stream sucessfully and have no problem with srt_close.  
I set following options for srt socket:
```
    SRTO_SNDSYN, 1
    SRTO_TSBPDMODE, 1
    SRTO_LATENCY, 2000
    SRTO_SNDTIMEO, 200
```
Please let me know, probably be I have missed some option, or help me to identify source of this issue - may be I can add some logging to find the fault?

**Comment by ethouris** [comment] 2018-03-02 11:52
This message appears when the number of packets in the sending queue (more precisely, the timespan between the first and last one) exceeds some threshold value, so the sender knows already that there's no point in sending this packet, as the receiver will drop it anyway, as it is too late already. In your case, with 2000ms latency, a packet that has to wait 2031ms for being sent is already doomed to be dropped.

This looks for me as the sending is too slow, but it's hard for me to determine the possible reason. Note that there can always be the case that the network throughput got a choke and sending with that bandwidth is at the moment not possible. Please try to rule this condition out somehow.

How easy and reliable is it to reproduce it? We have to try this ourselves.

**Comment by Gummilion** [comment] 2018-03-02 12:15
@ethouris - it was happen 5 out of 5 tries, and always at same time after start, I doubt it related to network conditions. Probably there is something iOS or ARM64-specific, so I may expect it will not been reproduced on other platforms. I will try to test with some other conditions to check what it may depend on.

**Comment by Gummilion** [comment] 2018-03-13 08:33
I found actual root cause of this issue.
Client stop to send data since server sends acknowledgement with only 2 free buffers, and it happens because of unexpected timestamp reset. Server holds buffers with wrong timestamps as it assume that buffers for future time, and soon run out of free buffers.
This caused since timestamps can be generated two ways: with `CTimer::getTime` or `CTimer::rdtsc` divided by `getCPUFrequency()`. For most platforms cases  `CTimer::rdtsc` simply calls `getTime` , but for macOS/iOS it calls `mach_absolute_time` , which returns number of ticks since power-up, while `getTime` returns microseconds of Unix epoch (since Jan 01 1970).
Both methods are OK until you tries to compare it: we have problem in core.cpp:6866
`if (origintime >= m_StartTime)` : `origintime` comes from `rdtsc`, while `m_StartTime` from `getTime`, and certainly `m_StartTime` is much bigger than `origintime`.
Also I wonder what that IA32/IA64/AMD64 conditions within `CTimer::rdtsc` are needed for - at least for Linux it goes to else switch anyway.
I made [a fix on my branch](https://github.com/Gummilion/srt/commit/26abfe6c7ffad5419a029d17a92abbec382680ed) , and was able to stream with it for 3 hours.
I have discussed it with associates, and we have doubts, does that ticks needed at all? Probably we can use microseconds in all cases  - just to remove condition for in `rtdsc` for macOS, and in `getTime` use this suggested method with `mach_absolute_time()` and `AbsoluteToNanoseconds()` to get microseconds: https://developer.apple.com/library/content/qa/qa1398/_index.html .
@ethouris - what is you opinion, how would you recommend to fix it? Probably you can suggest something else?

Also, I'm going to add compiler flags in iOS toolchain files to build library with debug symbols for xCode - is it OK to submit both fixes (with timestamps and debug symbols) in one pull request?

**Comment by Gummilion** [comment] 2018-03-14 03:09
I have created two pull requests: for [time caclulation](https://github.com/Haivision/srt/pull/301) and [adding debug information](https://github.com/Haivision/srt/pull/302) . 
By the way, I found that same issue take place on OS X as well: srt-live-transmit stucks in ~30 minutes without the fix, so this bug can easily been reproduced on macOS just with srt library without any additional software.

**Comment by alexpokotilo** [comment] 2018-03-14 03:21
@ethouris please bless https://github.com/Haivision/srt/pull/301 fix as it's vital for all Apple OSes including MacOS, IOS.
https://github.com/Haivision/srt/pull/302 fix helped us to find the problem. Without it mobile developer will not be able to debug SRT library code in X Code

**Comment by alexpokotilo** [comment] 2018-03-16 02:22
@ethouris we can close the ticket as #303 merged to dev. Thanks a lot!

**Comment by rndi** [comment] 2018-05-09 16:55
It appears that the fix is causing breakage elsewhere: the output of CTimer::getTime() is also used to schedule sleeps with pthread_cond_timedwait() and that function is using gettimeofday() internally to determine when to wake up. Currently, the result is tsbpd() thread looping hard and taking up next to 100% CPU on OSX. I wonder if you are seeing this too @Gummilion & @alexpokotilo?

**Comment by alexpokotilo** [comment] 2018-05-09 23:44
Hi @rndi,
we've started investigation. Is this problem reproduced immediately for IOS or we need to wait sometimes or do something to reproduce it ?

**Comment by rndi** [comment] 2018-05-10 00:42
Hello @alexpokotilo,

Thank you for the quick response!  I have only tested this on OSX but in my case, the conditions for OSX side are to be running in listener mode, a connection established, and traffic flowing through the connection. The issue does not occur when OSX side is in caller mode or no traffic is flowing. My sender/caller is a Linux machine.

Please note that I've identified additional CPU wasting for OSX in CEPoll::wait() that is unrelated to the current discussion. I don't know if you are using srt_epoll_wait() but if you do you might want to try commenting out all pre-processor conditionals around 'CTimer::waitForEvent()' call and the end CEPoll::wait() in epoll.cpp for additional CPU boost. I will open separate PR for this but it could be good if you can pre-check if the change works correctly on IOS. It will probably also help with the CPU measurements you are about to do.

**Comment by Gummilion** [comment] 2018-05-10 01:44
I have checked on macOS - **srt-live-transmit** in receive mode (`srt-live-transmit srt://ip:port file://con`) are generates 100% CPU load. I will work on fix.

**Comment by Gummilion** [comment] 2018-05-10 04:01
Even after reverting my #303 fix, stransmit still consumes 100% CPU, so I suppose it was not the root cause. I agree my code breaks some `pthread_cond_timedwait` calls, but seems it doesn't work properly on macOS anyway. @rndi, could you check stransmit without my fix (you may simply replace `#if` condition in `CTimer::getTime()` with `#if 0` to deactivate it).

**Comment by rndi** [comment] 2018-05-10 04:41
Hello @Gummilion ,
Please try to apply the change to epoll.cpp, along these lines:
```
--- a/srtcore/epoll.cpp
+++ b/srtcore/epoll.cpp
@@ -518,10 +518,7 @@ int CEPoll::wait(const int eid, set<SRTSOCKET>* readfds, set<SRTSOCKET>* writefd
       if ((msTimeOut >= 0) && (int64_t(CTimer::getTime() - entertime) >= msTimeOut * 1000LL))
          throw CUDTException(MJ_AGAIN, MN_XMTIMEOUT, 0);
 
-      #if defined(TARGET_OS_IOS) || defined(TARGET_OS_TV)
-      #else
       CTimer::waitForEvent();
-      #endif
    }
```
I am getting 4-6% CPU load on a Mac Mini with your fix commented out and the above change applied.

**Comment by Gummilion** [comment] 2018-05-10 06:44
I have created fix for timedwait in `tspbd()`, CPU consumption drop to normal with it. It's on my [timedwait](https://github.com/Gummilion/srt/tree/timedwait) branch, you can see delta [here](https://github.com/Haivision/srt/compare/dev...Gummilion:timedwait). Srt code has some other `pthread_cond_timedwait` calls that use getTime value, I suppose I should fix it as well. Probably I must create wrapper for timedwait that will accept timeout in microseconds?

**Comment by Gummilion** [comment] 2018-05-10 09:29
I have submitted pull request #378 - @ethouris , @rndi please review it.

**Comment by rndi** [comment] 2018-05-10 15:02
Thank you, @Gummilion , testing this now. At the first glance, the only comment I can make is that I would name the new function CTimer::condTimedWaitUS() for clarity but that's being picky.

Question: did you have to enable CTimer::waitForEvent() call in CEPoll::wait() for iOS in your tests (I know it has to be done for OSX, not sure about iOS)?

**Comment by Gummilion** [comment] 2018-05-11 00:45
@rndi - I was checked on macOS only. We don't receive SRT streams in our iOS projects, and we can't simply run stransmit on iOS, so I can't check it on iOS, unfortunately. We could add it to our iOS player, but it will take a while.

**Comment by rndi** [comment] 2018-05-11 01:10
Ok, thanks @Gummilion, I will leave iOS CEPoll::wait() logic as-is for now until there is an opportunity to test. Could you please consider re-naming CTimer::condTimedWait() to CTimer::condTimedWaitUS() and also look at the comments in PR #378 ? It needs some fixing.

**Comment by Gummilion** [comment] 2018-05-11 01:43
@rndi , I've created new branch [timedwait2](https://github.com/Gummilion/srt/tree/timedwait2) from master and added your changes there (in [this](https://github.com/Gummilion/srt/commit/80604be1f6e3f483a1e6802c83e2e8514d61e57d#diff-96b4e7e5e8ebad98634bfc0944aa3ce6) commit). I doubt whether adding US suffix is necessary. I added parameters description in common.h to precise it, probably it would be enough? However, I you persist, I can rename function.

**Comment by rndi** [comment] 2018-05-11 01:48
@Gummilion , thanks and yes, please, add the suffix. I know at least one more person other than myself that this small change will make a bit happier so why not :)

**Comment by Gummilion** [comment] 2018-05-11 02:35
OK, renamed function and created new PR #379

**Comment by maxlovic** [comment] 2019-02-05 09:57
Looks like can be closed. Please do not hesitate to reopen if I'm wrong.

**Closed by maxlovic** 2019-02-05 09:57 UTC
Labels: Status: Completed
