### ISSUE TITLE
[FR]The development Suggestions

### ISSUE THREAD

**Issue by ghost** [Haivision/srt#1660] opened 2020-11-14 11:03 UTC
For 20 years, ffmpeg, opencv, every open source has its focus areas and perfect and easy to understand and create, I propaganda of SRT streaming low delay very appreciate, also appreciate and thank you for this domain to focus and open source, but a project it again good, after all to return to the nature of things, our programmers need to do is, how to use it quickly understand and manipulate different platforms, and raise public awareness of it, so I suggest to add the sample program for each platform and compile the example for the use of the programmer, I think it will be a rapidly increasing popularity, and is widely used in streaming media it, of course, thanks to the open source.

**Comment by maxsharabayko** [comment] 2020-11-16 09:10
Hi @aixil123 
Thank you for your kind words!
At the moment there are simple example client and server available in the ["examples"](https://github.com/Haivision/srt/tree/master/examples) folder.
Furthermore, [srt-live-transmit](https://github.com/Haivision/srt/blob/master/apps/srt-live-transmit.cpp) can also be considered as a sample application, although a more complicated one.

**Comment by maxsharabayko** [comment] 2020-12-11 17:56
Closing. Nothing to do. The author of the issue is a ghost now.

**Closed by maxsharabayko** 2020-12-11 17:56 UTC
Labels: Type: Question
