### ISSUE TITLE
[BUG] [apps] IPv6 any address listener srt_bind error

### ISSUE THREAD

**Issue by vidanio** [Haivision/srt#2764] opened 2023-07-15 10:03 UTC
Latest commit version.

Commandline used:
`srt-live-transmit srt://[::]:5000?mode=listener udp://127.0.0.1:50001`

Error log:
`ERROR: error: srt_bind: Operation not supported: Bad parameters`

According to docs (https://github.com/Haivision/srt/blob/master/docs/apps/srt-live-transmit.md), it should work as a listener for both  IPv4 and IPv6. 

In fact with v1.5.1 worked fine.

Linux AMD 64 bits OS (Debian 11) machine

**Comment by ethouris** [comment] 2023-07-17 07:20
Ok, I got this. Sorry, this is likely not correctly explained in the documentation (@maxsharabayko likely we need a fix here).

The problem is with the `SRTO_IPV6ONLY` option, which reflects the `IPV6_V6ONLY` system option. There's no way to determine the current value of this option, and many internals depend on its value if you are using IPv6. It's not a problem for caller, but for listener SRT must be certain of its value. As SRT can't state what could be the default value, it's UNDETERMINED until set explicitly or until the first socket is created and the value obtained from it.

Therefore if you want to make a listener in IPv6, you have to add also the `ipv6only` option. Set it to 1 or 0, whatever you want, just it can't be left unset. By setting it to 0, of course, your listener will be able to accept callers that use IPv4.

**Comment by ethouris** [comment] 2023-07-17 09:52
#2765 was submitted to fix this in the documentaiton.

**Comment by ethouris** [comment] 2023-09-27 14:37
The problem was identified in the documentation and fixed there - closing. Please reopen if there's anything else.

**Closed by ethouris** 2023-09-27 14:37 UTC
Labels: Type: Bug
