### ISSUE TITLE
Receiver does not acknowledge receiving data

### ISSUE THREAD

**Issue by alvid** [Haivision/srt#680] opened 2019-05-08 16:46 UTC
Hi! I use SRT into FILE transfer mode. I run server at one host and two clients at another host. Each client sends data by timer to the server and that's all it doing. Since some time, server stops to confirm receiving data on the one connection. On the client side, I see an increase in the number of unconfirmed packets up to 8192 (maximum SRT). In fact, client stops to send any data to the server, but connection still alive. If I break second connection, the first connection may start working again.
The same problem appears with one client and server too.
I used version 1.3.2 and oldest with the same result.
The problem appears on both OS X and Linux.
I have logs and network dump and can send it to you.
Best regards, Aleksei.

**Comment by alvid** [comment] 2019-05-08 17:06
server log:2019-05-08 06:47:59.004 connection(233512340) statistics: TS:5000 send 0000 pkt/000000 bytes with rate 0.0000 mbps, send retransmit 000 pkt, recv 1028 pkt/1330496 bytes with rate 2.1285 mbps, recv lost 064 pkt, rtt 148.4 ms, EBW: 1.3600 mbps
2019-05-08 06:47:59.004 [INF] [ANT] connection(233512341): statistics: TS:5000 send 0000 pkt/000000 bytes with rate 0.0000 mbps, recv 0237 pkt/1288684 bytes with rate 2.0560 mbps
2019-05-08 06:47:59.004 [INF] [ANT] connection(233512341) statistics: TS:5000 send 0000 pkt/000000 bytes with rate 0.0000 mbps, send retransmit 000 pkt, recv 1029 pkt/1331856 bytes with rate 2.1307 mbps, recv lost 000 pkt, rtt 155.1 ms, EBW: 1.3600 mbps

**Comment by alvid** [comment] 2019-05-08 17:06
2019-05-08 06:47:59.004 [INF] [ANT] connection(233512340) statistics: TS:5000 send 0000 pkt/000000 bytes with rate 0.0000 mbps, send retransmit 000 pkt, recv 1028 pkt/1330496 bytes with rate 2.1285 mbps, recv lost 064 pkt, rtt 148.4 ms, EBW: 1.3600 mbps
2019-05-08 06:47:59.004 [INF] [ANT] connection(233512341): statistics: TS:5000 send 0000 pkt/000000 bytes with rate 0.0000 mbps, recv 0237 pkt/1288684 bytes with rate 2.0560 mbps
2019-05-08 06:47:59.004 [INF] [ANT] connection(233512341) statistics: TS:5000 send 0000 pkt/000000 bytes with rate 0.0000 mbps, send retransmit 000 pkt, recv 1029 pkt/1331856 bytes with rate 2.1307 mbps, recv lost 000 pkt, rtt 155.1 ms, EBW: 1.3600 mbps

**Comment by alvid** [comment] 2019-05-08 17:15
Server log:
1) all's good
2019-05-08 06:47:59.004 connection(233512340) statistics: send 0000 pkt/000000 bytes with rate 0.0000 mbps, send retransmit 000 pkt, recv 1028 pkt/1330496 bytes with rate 2.1285 mbps, recv lost 064 pkt, rtt 148.4 ms, EBW: 1.3600 mbps
2019-05-08 06:47:59.004 connection(233512341) statistics: send 0000 pkt/000000 bytes with rate 0.0000 mbps, send retransmit 000 pkt, recv 1029 pkt/1331856 bytes with rate 2.1307 mbps, recv lost 000 pkt, rtt 155.1 ms, EBW: 1.3600 mbps

2) there are lost of data for connection 233512340 and RTT increases, but not for connection 233512341
2019-05-08 06:48:04.009 connection(233512340) statistics: send 0000 pkt/000000 bytes with rate 0.0000 mbps, send retransmit 000 pkt, recv 2052 pkt/2653968 bytes with rate 4.2426 mbps, recv lost 603 pkt, rtt 464.4 ms, EBW: 1.3600 mbps
2019-05-08 06:48:04.009 connection(233512341) statistics: send 0000 pkt/000000 bytes with rate 0.0000 mbps, send retransmit 000 pkt, recv 2814 pkt/3642240 bytes with rate 5.8224 mbps, recv lost 263 pkt, rtt 154.2 ms, EBW: 1.3600 mbps

3) after 40 seconds no receive data for connection 233512340
2019-05-08 06:48:44.015 connection(233512340) statistics: TS:5000 send 0000 pkt/000000 bytes with rate 0.0000 mbps, send retransmit 000 pkt, recv 0000 pkt/000000 bytes with rate 0.0000 mbps, recv lost 000 pkt, rtt 464.4 ms, EBW: 1.3600 mbps
2019-05-08 06:48:44.015 connection(233512341) statistics: TS:5000 send 0000 pkt/000000 bytes with rate 0.0000 mbps, send retransmit 000 pkt, recv 1632 pkt/2111808 bytes with rate 3.3784 mbps, recv lost 000 pkt, rtt 233.0 ms, EBW: 1.3600 mbps

Client log:
1) 2019-05-08 06:47:55.773 connection(143538764) statistics: send 1648 pkt/2132512 bytes with rate 3.3438 mbps, retransmit 000 pkt, non-acked 60 pkt recv 0000 pkt/000000 bytes with rate 0.0000 mbps, lost 000 pkt, rtt 149.5 ms, estimate bw: 56.0320 mbps

2) 2019-05-08 06:48:00.898 connection(143538764) statistics: send 7049 pkt/9120416 bytes with rate 14.2384 mbps, retransmit 5385 pkt, non-acked 1206 pkt recv 0000 pkt/000000 bytes with rate 0.0000 mbps, lost 000 pkt, rtt 283.6 ms, estimate bw: 48.1984 mbps

3) 2019-05-08 06:48:46.937 connection(143538764) statistics: send 0000 pkt/000000 bytes with rate 0.0000 mbps, retransmit 000 pkt, non-acked 8192 pkt recv 0000 pkt/000000 bytes with rate 0.0000 mbps, lost 000 pkt, rtt 283.6 ms, estimate bw: 48.1984 mbps

**Comment by alvid** [comment] 2019-05-08 17:16
All statistics are obtained using the function srt_bistats()

**Comment by ethouris** [comment] 2019-05-09 07:04
Debug logs if you can collect it would be most useful. See docs/reporting.md for details on how to get them.

If you can better one connection by closing the other, it looks like some kind of deadlock. I hope this is reproducible.

**Comment by alvid** [comment] 2019-05-12 13:31
Please, see issue: https://github.com/Haivision/srt/issues/689

**Comment by alvid** [comment] 2019-05-12 17:04
Please, see my post https://github.com/Haivision/srt/issues/688#issuecomment-491599113

**Comment by alvid** [comment] 2019-05-13 12:55
You may use our sample to reproduce the problem, see at:
https://github.com/SteppeChange/srt_test/tree/master/libant

**Comment by maxsharabayko** [comment] 2024-08-07 09:11
Closing as stale.

**Closed by maxsharabayko** 2024-08-07 09:11 UTC
Labels: Type: Bug, [core]
