### ISSUE TITLE
TL Packet Drop supresses MAXBW limitation

### ISSUE THREAD

**Issue by maxsharabayko** [Haivision/srt#713] opened 2019-05-30 13:52 UTC
When TL packet drop is turned on, **and input bitrate exceeds the maxbw limitation**, the  MAXBW limit is suppressed. This can happen also when the amount of retransmission is high (see #638).
By default maxbw is limited to 1 Gbps (30 Mbps prior to v1.3.3).
Latest on the moment of testing SRT version 6f6b76b381ba8854fcd699908f74fae4cfce6783.
URI query both for receiver and sender: 
`transtype=live&messageapi=1&payloadsize=1456&rcvbuf=125000000&sndbuf=125000000`
Link RTT is 0.24 ms (local 1 Gbps switch).

Sender sends packets at 900 Mbps. Nothing stops it. But looks like the receiver is ackowleding packets at slower rate, thus the sender's buffer gets full.

E.g. this query actually limits sending rate to 30 Mbps:
`transtype=file&congestion=live&messageapi=1&payloadsize=1456&rcvbuf=125000000&sndbuf=125000000`
The difference is that TL packet drop is turned off by `transtype=file` (there is no URI query socket option to turn off TSBPD directly).

Sender side packets. Notice the packets start dropping only at the end. And the sender starts printing error messages: `SND-DROPPED 893 packets - lost delaying for 1032ms`.
![win-900Mbps-test-04-snd-packets](https://user-images.githubusercontent.com/12700120/58636530-da6f4d00-82f0-11e9-9435-7d13754e94c6.png)

And the packets start dropping when the available sender's buffer size goes down to 0:
![win-900Mbps-test-04-snd-availbuffer](https://user-images.githubusercontent.com/12700120/58636571-eeb34a00-82f0-11e9-9dc3-d070be0e01ee.png)

While the time interval between the packets is 400 μs, that corresponds to 30 Mbps.
![win-900Mbps-test-04-snd-pktsendperiod](https://user-images.githubusercontent.com/12700120/58636611-fffc5680-82f0-11e9-886b-ce458c90016c.png)

Receiving rate:
![win-900Mbps-test-04-rcv-packets](https://user-images.githubusercontent.com/12700120/58636698-2b7f4100-82f1-11e9-9d12-c618e1fbb8e7.png)

The receiver's buffer size, although set to 1 GB, is actually limited by FC size, so it is actually only 300 Mbits (refer to #700).
![win-900Mbps-test-04-rcv-availbuffer](https://user-images.githubusercontent.com/12700120/58636765-523d7780-82f1-11e9-8453-8d96558b5e1f.png)

In the end receiver closes the connection due to:
`SRT:RcvQ:worker*E:SRT.c: %915948307:SEQUENCE DISCREPANCY, reception no longer possible. REQUESTING TO CLOSE.`

Setting `maxbw=125000000` solves the problem, although in the described set up the size of the recevier's buffer is too small, and it anyway closes the connection with error message:
```
SRT:RcvQ:worker*E:SRT.c: %488590918:No room to store incoming packet: offset=0 avail=0 ack.seq=2032363150 pkt.seq=2032363150 rcv-remain=25599
SRT:RcvQ:worker*E:SRT.c: %488590918:No room to store incoming packet: offset=1 avail=0 ack.seq=2032363150 pkt.seq=2032363151 rcv-remain=25599
```

But notice the receiving rate is 900 Mbps:
![win-900Mbps-test-05-rcv-rate](https://user-images.githubusercontent.com/12700120/58637196-4bfbcb00-82f2-11e9-98aa-e7286b91d22d.png)

While for the case when `maxbw=30` Mbps the receiving rate is actually lower:
![win-900Mbps-test-04-rcv-rate](https://user-images.githubusercontent.com/12700120/58637237-5e760480-82f2-11e9-8afe-def6373350aa.png)

Also refer to #553, where almost similar experiment was conducted.

**Comment by jeandube** [comment] 2019-05-30 14:10
There is an option (SRTO_TSBPDMODE) to turn TSBPD on/off, You probably means no URI query.

**Comment by jeandube** [comment] 2019-05-30 14:11
If all issues were presented that way, I can't imagine where SRT would be.

**Comment by maxlovic** [comment] 2019-05-30 14:16
@jeandube 
> There is an option (SRTO_TSBPDMODE) to turn TSBPD on/off, You probably means no URI query.

Yes. Improved the description. Thank you, Jean.

> If all issues were presented that way, I can't imagine where SRT would be.

I am looking forward to have a cool automated toolset for such cool things. 😄

**Comment by alexpokotilo** [comment] 2019-05-31 08:46
"While the time interval between the packets is 400 μs, that corresponds to 30 Mbps."
it should be 12.9422222222μs for 900MBps if we send one packet at time. Do you mean SRT sends ~30packets each time ?

Another question.
if I use live(TSBPD is on) and  set maxbw to value greater stream max sending rate just to limit re-transmission traffic can I expect maxbw will still work ?
Is this problem reproduced only if actual stream bandwidth > 30Mbps or lower limits may be suppressed too ?
When and how maxbw works at all ? :) I just relaxed thinking I got your explanation from #638 before I read this:)

**Comment by maxlovic** [comment] 2019-05-31 10:01
@alexpokotilo 
> Is this problem reproduced only if actual stream bandwidth > 30Mbps or lower limits may be suppressed too ?

Yes, the problem is in the "abnormal" usage scenario, when actual input bitrate exceeds maximum bandwidth value. In this case it looks like packet origin time somehow gains priority over the desired time intervals between the packets.
In the normal usage scenario (input bitrate < maxbw) maxbw should work, so no worries. 🙂

**Comment by maxlovic** [comment] 2019-05-31 11:04
Further investigation shows that waiting gets interrupted from [`CSndUList::update`](https://github.com/Haivision/srt/blob/master/srtcore/queue.cpp#L317) and [`CSndUList::insert`](https://github.com/Haivision/srt/blob/master/srtcore/queue.cpp#L300).
As we know, [CTimer::interrupt](https://github.com/Haivision/srt/blob/master/srtcore/common.cpp#L235) resets target time, unlike just [`CTimer::tick'](https://github.com/Haivision/srt/blob/master/srtcore/common.cpp#L241).
Looking further into this.

**Comment by maxlovic** [comment] 2019-05-31 14:33
Most probably [`NeedDrop(Ref(bCongestion))`](https://github.com/Haivision/srt/blob/master/srtcore/core.cpp#L5289) decides to drop packets when TSBPD is enabled,
Because of that the sending is rescheduled by calling [m_pSndQueue->m_pSndUList->update(this, CSndUList::rescheduleIf(bCongestion))](https://github.com/Haivision/srt/blob/master/srtcore/core.cpp#L5396) with `bCongestion=true`. And that triggers sending the packet that should have waited 400 us instead.

**Comment by ethouris** [comment] 2019-08-07 08:01
> Most probably [`NeedDrop(Ref(bCongestion))`](https://github.com/Haivision/srt/blob/master/srtcore/core.cpp#L5289) decides to drop packets when TSBPD is enabled,

Dropping packets is controlled by the `SRTO_TLPKTDROP` option. This has nothing to do with TSBPD, only without this option it will work more clumsily. Note that `SRTO_TRANSTYPE` controls all these options.

**Comment by maxlovic** [comment] 2019-08-07 08:45
Yes, I was thinking of TSBPD and TL packet drop mechanisms as a single. In fact this is about TL packet drop.

**Comment by maxlovic** [comment] 2019-10-08 14:47
Update. TL Packet drop mechanism triggers sending of the next scheduled packet after 
`timespan_ms > (m_iPeerTsbPdDelay_ms/2)`
where `timespan_ms` is the time difference between the very first packet in the sender's buffer, and the latest packet in the sender's buffer.

**Comment by stoneljp** [comment] 2021-01-18 01:46
when i use srt live and set transtype=0 tsbpdmode=false tlpktdrop=0  
it still has SND-DROP， then socket close
then  change parameters to the above I can send a 60Mbps streaming very perfect  no mosaic no socket closing

**Closed** 2022-01-26 03:37 UTC
Labels: Priority: High, Type: Bug, [core]
