### ISSUE TITLE
transfer quality about SRT

### ISSUE THREAD

**Issue by whu-ysw** [Haivision/srt#1129] opened 2020-02-13 05:10 UTC
I'm the new to **srt**, and set up whole environment in Windows 7 by documents. However, the video quality can't satisfy common use in daily life. The VLC srceen is blurred as following picture shows. Maybe I should do something to improve video quality. Could someone help me? Thanks in advance.

![problemDescription](https://user-images.githubusercontent.com/18614371/74403033-e8560580-4e60-11ea-9c48-23ca3481de85.png)

Following code is my configuration：
FFmpeg configuration:
`ffmpeg -r 30 -re -i test.mp4 -pix_fmt yuv420p -c:v libx264 -b:v 1000k -profile:v baseline -preset ultrafast -f mpegts "udp://127.0.0.1:5000?pkt_size=1316"`
srt configuration:
`srt-live-transmit.exe udp://5000 srt://:9000`

**Comment by dfloer** [comment] 2020-02-23 01:29
One helpful piece of troubleshooting is to see what is going with on VLC's end. You can select `Tools -> Messages` (apologies, I don't know what those are not in English) and then select verbosity: 2 (debug). There'll be a lot of general VLC debug messages (volume change, mouse clicks and the like), but it should at least help you narrow down what VLC is having issues with.

I've also found it helpful when troubleshooting to turn the verbosity of srt-live-transmit's stats up, I usually use `srt-live-transmit -s 100 -v -f`. Easy to see if I'm dropping a lot of packets, etc.

**Comment by whu-ysw** [comment] 2020-02-23 07:08
It's really helpful for me to turn on VLC debug option. I should analyse the error messages carefully. Thanks for your instructions.

**Comment by mkdryden** [comment] 2020-02-23 23:30
I am having similar issues. I think the problem is that there are continuity issues in the MPEG-TS stream. Testing with a similar setup (both ffmpeg and srt-live-transmit on the same Windows 10 system), I don't see any lost or dropped packets in srt's stats, but VLC shows a ton of messages like this:

```
ts warning: discontinuity received 0xa instead of 0xf (pid=256)
main warning: playback way too early (-131786): playing silence
main warning: picture is too late to be displayed (missing 1778 ms)
main warning: playback too early (-44580): down-sampling
```

and piping it through tsduck and using the continuity tool, there is a constant string of missing packets:

`* continuity: packet index: 747,191, PID: 0x0100, missing 8 packets`

I did have some success in getting a better quality stream by fiddling with ffmpeg's encoder settings; some settings produce mostly watchable video with glitches only every few seconds, and others are essentially blank video (though the audio track seems less problematic). I'm not sure if this is an ffmpeg problem or just masking over a problem somewhere else. I am aware that ffmpeg is not amazing at doing MPEG-TS, and doing just UDP to UDP with tsduck does show some continuity issues, but far less than using srt.

**Comment by mkdryden** [comment] 2020-02-25 00:53
Actually, testing further, I don't see this problem using ffmpeg with libsrt support instead of srt-live-transmit, so this is perhaps just #933 (though I see it at bitrates below 8M).

**Comment by whu-ysw** [comment] 2020-02-25 02:57
Thanks a lot. Maybe using FFMpeg with libsrt is good choice worth to try. The version I use now is a static version without libsrt support. I need to google to look for some articles for how build it. Actually, I have tried all these configurations in Ubuntu14.04 LTS and Ubuntu18.04 LTS in VMWare. Configurations were completed successfully, but it doesn't work. There is no any video or audio I can get in the receiver. Instread, I deploy in Windows 7 system. The voice is retrieved finally.  By the way, it  is so tedious to compile in Windows.

**Comment by maxsharabayko** [comment] 2020-02-25 06:07
A short guide on FFMpeg + srt: [link](https://srtlab.github.io/srt-cookbook/apps/ffmpeg/)

**Comment by whu-ysw** [comment] 2020-02-25 07:52
Wow, that's a good instruction. Thank you very much. A short guide is more easy to understand for a newbie.

**Comment by maxsharabayko** [comment] 2020-02-25 08:21
SRT can be built on Windows using vcpkg manager. Vcpkg builds the dependencies (pthreads and OpenSSL) without the need to manually configure everything.
[Instructions](https://srtlab.github.io/srt-cookbook/getting-started/vcpkg-library-manager/) (see 2nd option).

**Comment by whu-ysw** [comment] 2020-02-26 08:56
Sorry, I don't look up my email yesterday later. Thanks to remind me of this important infomation. Using vcpkg is really a better choice to a Windows user. After building SRT, I should learn about some related concepts and set parameters carefully to improve the video effect.

**Comment by J-Rogmann** [comment] 2020-10-22 11:56
Hello @whu-ysw 

I'm working through some old tickets, which are still left open. Did you manage to build it? Do you still experience any issues? Or can we close this ticket?

best regards,
Justus

**Comment by whu-ysw** [comment] 2020-10-22 13:50
> Hello @whu-ysw
> 
> I'm working through some old tickets, which are still left open. Did you manage to build it? Do you still experience any issues? Or can we close this ticket?
> 
> best regards,
> Justus

My problem has been solved already, you can close this ticker now. Thanks.

**Closed** 2020-10-22 14:55 UTC
Labels: Type: Question
