### ISSUE TITLE
srt-test-live with groupconnect=true listener - responds with one IP address for all connections?

### ISSUE THREAD

**Issue by petrn** [Haivision/srt#1777] opened 2021-01-31 21:15 UTC
Hello,

I am trying to set up a simple bonding POC with type=balancing.

My listener side looks like this:

srt-test-live "udp://239.192.101.12:5000/?adapter=192.168.101.104" -g "srt://:1234?groupconnect=true" -v

and the machine this is running on has 4 LAN interfaces each on a separate subnet, where 3 of those [address1..3] are supposed to be used for the separate connections to be bonded and address4 is the remaining interface mean for management (this has the default route with lowest metric).

My caller side looks like this (and is behind a NAT):

srt-test-live  "srt://address1:1234?type=balancing" "srt://address2:1234?type=balancing" "srt://address3:1234?type=balancing"  -g udp://239.192.192.192:5000

But the above does not work at all for the following reason:

the connections are made to the address1 to address3, port 1234, so they all and up at the correct listener. The listener receives the first UDP datagram on each connection, but all the answers come out with the address4 as source address. The the  NAT never delivers the response to the caller, as it does not come from the same IP address as was the initial request.

I have initially tried a simpler setup where I have just assigned multiple IP addresses to the same interface on the listener side. But the result was the same. I have hoped that splitting this to multiple networks might help, but it did not.

So I am confused how is it supposed to work (as the above is more or less the example in the documentation), or if nobody has ever tried to run this from behind a NAT on the caller side. The caller is on multiple LTE connections so it is not possible to avoid the NAT for the caller (and it cannot be a listener for the same reason).

Is there any way in srt_test_live to ensure the responses are sent from the same IP address as the one which was used as destination for the UDP?

I have tried to specify multiple destinations bound to the respective adapter, but that did not seem to work either.

Any suggestion anybody?

**Comment by J-Rogmann** [comment] 2021-02-01 15:51
Hi @petrn 
Currently `type=balancing` is not supported, even when enabling "experimental" features. Only `broadcast` and `backup` are available as of today. For now I also don't have a time frame, how long we will need to implement it.

**Comment by petrn** [comment] 2021-02-01 15:57
Hi @J-Rogmann 
OK, so I have tried to change from type=balancing to type=broadcast and I get the same results. I need to use different IP addresses on the listener side so that the connections are routed through different path (different LTE modem each), but the response comes from a different IP address and thus never reaches the caller through the NAT.

So while I ultimately want to use the balancing, the problem I am facing seems to be independent on the mode of the group.

**Comment by ethouris** [comment] 2021-02-01 16:11
There's a simpler syntax you can use (caller mode):
```
srt-test-live srt://*?type=broadcast address1:1234 address2:1234 address3:1234 -g udp://<whatever...>
```
Note also that in the LISTENER mode you should **not** use the -g option - this option is only for caller side. This option is only required to be able to specify multiple endpoints for the caller, that's all (without it, the application expects exactly one source and one destination specification).

In case of listener mode, the application handles single-socket connection as well as group-connection (of which the latter is only extra allowed by the `groupconnect=1` option), and the application recognizes which case it is automatically.

**Comment by petrn** [comment] 2021-02-01 16:17
Hi @ethouris ,

yes, I am aware of that and I have been trying to use it on the caller side. But this is what I was getting - so the more verbose syntax at least tries to send something out, while this syntax simply dies.

This the master branch from git as of yesterday....

SRT parameters specified:

	type = 'broadcast'

```
Opening SRT source caller(blocking, backlog=1) on *:0
Connecting to *:0 ... FAILURE
srt_connect: [5003.0] Operation not supported: Bad parameters
Open FAILED - closing SRT sockets
MEDIA CREATION FAILED: error: srt_connect: Operation not supported: Bad parameters - exiting.
```

**Comment by ethouris** [comment] 2021-02-01 16:27
Please show me the contents of `config-status.sh` file in your build directory.

**Comment by petrn** [comment] 2021-02-01 16:29
I have used the config for this particular build...

```
#!/bin/bash
./configure --enable-testing
```

**Comment by ethouris** [comment] 2021-02-01 16:30
You need additionally `--enable-experimental-bonding`, otherwise this functionality is off.

**Comment by petrn** [comment] 2021-02-01 16:36
@ethouris 

Thanks for the hint, I have not been aware of that...

However, now on the listener side, I have the following:

```
./srt-test-live -r 20000 -s 20000 "udp://239.192.101.12:5000/?adapter=192.168.101.104&rcvbuf=$((16*1024*1024))"  "srt://:1234?groupconnect=true" -v
Multicast: home address: 192.168.101.104:5000
Multicast(POSIX): will bind to IGMP address: 239.192.101.12
SRT parameters specified:

	groupconnect = 'true'

Opening SRT target listener(blocking, backlog=10) on :1234
WARNING: failed to set options:
groupconnect,

ERROR (app): ConfigurePre
Open FAILED - closing SRT sockets
MEDIA CREATION FAILED: ConfigurePre - exiting.
```

Is the option no longer needed or is now called something else?

**Comment by ethouris** [comment] 2021-02-01 16:39
`groupconnect=1` should be specified (we changed later the type of the value because we expected something more complicated to be specified, but now that's left for future).

**Comment by petrn** [comment] 2021-02-01 16:42
OK, now the syntax is accepted, but the original problem is still the same. The request comes to - say - address1 but the response is sent from address4 rather than address1. This is being monitored by tcpdump...

**Comment by J-Rogmann** [comment] 2021-02-01 16:47
did you freshly compile on both ends with `--enable-testing` AND `--enable-experimental-bonding` ?

**Comment by petrn** [comment] 2021-02-01 16:50
yes, that is exactly what I have done - both ends are compiled with the above options. The listener side uses the original command line (with the change of =1 instead of =true), the caller side is now using the "new" syntax with the asterisk. So the command line parsing has changed, but the underlying behaviour seems to be the same - the caller does send 3 requests, one for each address, the listener does receive them, but answers them all from the same (and different) IP address. As this goes through a NAT, the responses never reach the caller....

**Comment by ethouris** [comment] 2021-02-01 16:56
What happens if you try a single-socket connection over `address1`?

There is a known problem in the following case: if you have multiple local IP addresses that share the common "broadcast" scheme, the connection will not be possible. Maybe that's your case.

The problem can be shortly described as:
You have the following local IP addresses, all of them with mask: 255.255.255.0:

* 192.168.10.5
* 192.168.10.120
* 10.5.5.10

The first two addresses have both the broadcast scheme: 192.168.10.0.

If you have this case, you might get the listener response coming from the wrong source IP address, and if so, connection on that address will not be possible.

**Comment by petrn** [comment] 2021-02-01 17:02
@ethouris 

That is how I have started. Now I have 3 separate LANs with proper masks on 3 separate interfaces on the listener side...

```
eth0      Link encap:Ethernet  HWaddr 00:0c:29:d5:1f:81
          inet addr:192.168.251.234  Bcast:192.168.251.255  Mask:255.255.255.0

eth1      Link encap:Ethernet  HWaddr 00:0c:29:d5:1f:8b
          inet addr:192.168.101.104  Bcast:192.168.101.255  Mask:255.255.255.0

eth2      Link encap:Ethernet  HWaddr 00:0c:29:d5:1f:95
          inet addr:10.147.147.2  Bcast:10.147.147.3  Mask:255.255.255.252

eth3      Link encap:Ethernet  HWaddr 00:0c:29:d5:1f:a9
          inet addr:10.147.147.6  Bcast:10.147.147.7  Mask:255.255.255.252
 
eth4      Link encap:Ethernet  HWaddr 00:0c:29:d5:1f:9f
          inet addr:10.147.147.10  Bcast:10.147.147.11  Mask:255.255.255.252
```

the address1, 2 and 3 are those 10.147.147.x addresses of eth2 to 4. But the answers are sent from eth0 address (eth1 is the interface with the input UDP stream).

Routing:

```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.251.1   0.0.0.0         UG    202    0        0 eth0
0.0.0.0         10.147.147.1    0.0.0.0         UG    204    0        0 eth2
0.0.0.0         10.147.147.5    0.0.0.0         UG    205    0        0 eth3
0.0.0.0         10.147.147.9    0.0.0.0         UG    206    0        0 eth4
10.147.147.0    0.0.0.0         255.255.255.252 U     204    0        0 eth2
10.147.147.4    0.0.0.0         255.255.255.252 U     205    0        0 eth3
10.147.147.8    0.0.0.0         255.255.255.252 U     206    0        0 eth4
```

**Comment by petrn** [comment] 2021-02-01 17:05
a single socket connection on address1 has the same issue as the group connection - only the address4 (eth0) works for single socket connection.

**Comment by petrn** [comment] 2021-02-01 17:08
the caller side is Ubuntu 20.04 but the listener side is an older Debian 8 (Jessie). The different metrics have been set up by the OS, these have not been set manually. Perhaps that is the source of the problem that the default route via eth0 has a lower metric than the other interfaces.

**Comment by J-Rogmann** [comment] 2021-02-01 17:09
this smells like a routing problem, indeed

**Comment by ethouris** [comment] 2021-02-01 17:12
Ok, just as I thought. I'll try to explain.

The problem is with the listener side responding to the handshake from the caller, and that it selects the Source IP address that will be then filled in the UDP header. This source IP address will be selected basing on the route path to the destination IP address - this thing happens inside the system on the UDP level. The caller checks the source address from which the packet has come and if it doesn't match the address to which the request was sent, the packet is rejected.

This might be also on the other party - the source address used by the handshake packet of the caller isn't exactly the address to which it expect to receive response packets from the listener.

OTOH there could exist a method to mitigate this, if you bind the address explicitly to the IP address. Please try first with the single socket and setting `adapter` to the explicit IP address on the listener side.

**Comment by petrn** [comment] 2021-02-01 17:19
OK, now my routing is like this:

```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.147.147.9    0.0.0.0         UG    202    0        0 eth4
0.0.0.0         10.147.147.5    0.0.0.0         UG    202    0        0 eth3
0.0.0.0         10.147.147.1    0.0.0.0         UG    202    0        0 eth2
0.0.0.0         192.168.251.1   0.0.0.0         UG    202    0        0 eth0
```

Note the order they are listed above.

Attempting a single-socket connection to address1 (on eth2) does respond with the address3 (on eth4, the first in the list).

So the single socket connection still does not work with address1 (but it now works with address3, or whatever address is first in the routing table). All the responses (regardless of address) are now coming from 10.147.147.10 via 10.147.147.9

**Comment by ethouris** [comment] 2021-02-01 17:25
It works with address3 because on the peer side this is the address set as source for sending to whichever of the addresses you attempt.

Note that you can also set adapter for the caller side (same `adapter` option). Try with explicitly specified adapter. When a UDP socket is bound to an explicit IP address, it WILL use this address as source, no matter where it sends the data, as long as the target address is reachable through the route path available for this source address.

**Comment by ethouris** [comment] 2021-02-01 17:41
Ah, of course note that if you succeed for single-socket connection, you might try the same with bonded connection. SRT allows to use multiple listeners to handle group connections (adding to group is by group identifier, so a group connection will join the right group at the listener side no matter to which listener the member connection was reported). Just you need to use the `srt-test-mpbond` application at the listener side because `srt-test-live` doesn't feature multiple listeners.

**Comment by petrn** [comment] 2021-02-01 18:04
OK, the srt-test-mpbond and using individual adapters sounds like a possible way to go. I will give this a try...

However, I am curious how are you doing your testing and how are others using this. You need more than 1 address so that the connections are routed over a different path, but of course if you have no NAT in the middle, the responses will reach you even if they do not come from the same addresses as you have sent the request to. I am not sure if I am missing something here or if the whole design is not really NAT friendly (but with mobile connections you cannot avoid the NAT unless you would use VPN which would add overhead and the normal 7 TS packets would no longer fit into a single IP datagram over the VPN.

**Comment by ethouris** [comment] 2021-02-01 18:13
For example: we have 4 devices - say, eth5, 6, 7, 8.

We give them addresses like: 10.0.5.1, 10.0.6.1, 10.0.7.1, 10.0.8.1, on the other side they are kinda like 10.0.5.2 etc. - and for all of them the mask is 255.255.255.0 and they have a usual broadcast scheme like 10.0.5.0 etc.

**Comment by petrn** [comment] 2021-02-01 18:15
using srt-test-mpbond on the listener side does at least create all the connections.

```
./srt-test-mpbond  10.147.147.2:1234 10.147.147.6:1234 10.147.147.10:1234 -i "udp://239.192.101.12:5000/?adapter=192.168.101.104&rcvbuf=$((16*1024*1024))"
```

and on the caller side:

```
 ./srt-test-live srt://*?type=broadcast address1:1234 address2:1234 address3:1234 -g udp://239.192.192.192:5000 -v
```

this starts well but then it fails, most likely due to the fact that none of the connections is capable to carry the whole stream.

```
NOTE: INPUT specification set as: srt:////group?type=broadcast&nodes=address1:1234,address2:1234,address3:1234,
SRT parameters specified:

	nodes = 'address1:1234,address2:1234,address3:1234,'

	type = 'broadcast'

Opening SRT source caller(blocking, backlog=1) on :0
REDUNDANT connections with 3 nodes:
Connecting to nodes:
	[1] address1:1234
	[2] address2:1234
	[3] address3:1234
Waiting for group connection... [ASYNC] will wait...SUCCESSFUL
Setting RCV blocking mode: true timeout=0
Setting RCV blocking mode: true timeout=0
Group connection report:
@190583889 <CONNECTED> (=0) PEER:address1:1234
@190583888 <CONNECTING> (=0) PEER:address2:1234
@190583887 <CONNECTING> (=0) PEER:address3:1234
ENCRYPTION status: UNSECURED (SND:UNSECURED RCV:UNSECURED) PBKEYLEN=0
OPTIONS: maxbw=-1 rcvlatency=120 blocking{rcv=true snd=true} snddropdelay=0
Multicast: home address: INADDR_ANY:5000
Multicast(POSIX): will bind to IGMP address: 239.192.192.192
STARTING TRANSMISSION: 'srt:////group?type=broadcast&nodes=address1:1234,address2:1234,address3:1234,' --> 'udp://239.192.192.192:5000'
[. << ... 19:09:32.646088/srt-test-live*E:SRT.gr: group/recv: all links broken
FAILURE
srt_recvmsg2: [2002.0] Connection does not exist
STD EXCEPTION: error: srt_recvmsg2: Connection does not exist
Waiting 5s for possible cleanup...
SrtCommon: DESTROYING CONNECTION, closing socket (rt%1264325714)...
SrtCommon: ... done.
```

**Comment by petrn** [comment] 2021-02-01 18:18
@ethouris OK, then I have the same, but I have used the /30 mask instead of /24. I can test if it makes any difference, but provided the addresses match the masks I do not see why it would not work.

What is the source IP of the responses in your setup? What kind of OS is that running on?

But have you ever tried to have the caller behind a NAT? I suppose you would then run into the same issues as I did.

**Comment by ethouris** [comment] 2021-02-01 18:43
We usually test on Linux, but this thing happens the same way on every system. We were trying to find some solution for this, it's in #431. The fix was never merged because we couldn't prove it won't burden the performance during transmission.

I'm kinda confused with your configuration, and broadcast in your report doesn't look exactly as I imagine, but there is such a value of IP address that is a result of `ADDRESS & MASK`. For 1.2.3.4 & 255.255.255.0 it results with 1.2.3.0.

So, if you make this operation on every local IP address on the machine, and if you have at least one case that for multiple local IP addresses you get the same value of mask-cleared IP address (that is, these values are not unique), then a group of local IP addresses that have the same mask-cleared IP will function under a common source IP address, which will be the first of them all in the order of rules in the routing table.

**Comment by petrn** [comment] 2021-02-01 18:53
I will review #431, this is my 2nd day trying to use srt, so I have by no means any idea of what the current pending issues are.

Regarding network masks, the /30 is the longest mask you can have - it only leaves 2 bits for the host part and 2 out of the 4 possibilities are taken by the net and broadcast addresses, so it leaves just 2 options for the hosts. So effectively the old way to address a point-to-point connection (that is how all dial-up users were handled in the mid-90s). So my setup does meet your requirements, unless there is some stupid typo or something like that.

When you apply the mask to my addresses, you will get 10.147.147.0, 10.147.147.4 and 10.147.147.8 - so these do not overlap and are unique. But I will test the same with normal /24 masks if it makes any difference, if yes, it might suggest some issue with the address/mask arithmetic in the srt implementation. I will also review this part of the source code if I can make any sense out of it.

**Comment by ethouris** [comment] 2021-02-02 08:35
Again: this isn't something in SRT. This is UDP and the routing table. SRT has no influence on what the source address is set in the UDP  packet (and actually the issue I gave you above was a request to be able to have this influence). Yes, your addresses look ok, that is, they don't share the same network address. Would you be able to grab a pcap from the session in which you try to make a single connection with the configuration that fails? At least we'll see what happens on the system level.

**Comment by petrn** [comment] 2021-02-02 08:53
@ethouris here are the PCAPs you have requested

To keep things together in 1 place, this is the listener side:

Interfaces:
```
eth0      Link encap:Ethernet  HWaddr 00:0c:29:d5:1f:81
          inet addr:192.168.251.234  Bcast:192.168.251.255  Mask:255.255.255.0

eth1      Link encap:Ethernet  HWaddr 00:0c:29:d5:1f:8b
          inet addr:192.168.101.104  Bcast:192.168.101.255  Mask:255.255.255.0

eth2      Link encap:Ethernet  HWaddr 00:0c:29:d5:1f:95
          inet addr:10.147.147.2  Bcast:10.147.147.3  Mask:255.255.255.252

eth3      Link encap:Ethernet  HWaddr 00:0c:29:d5:1f:a9
          inet addr:10.147.147.6  Bcast:10.147.147.7  Mask:255.255.255.252

eth4      Link encap:Ethernet  HWaddr 00:0c:29:d5:1f:9f
          inet addr:10.147.147.10  Bcast:10.147.147.11  Mask:255.255.255.252
```

routing:
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.147.147.9    0.0.0.0         UG    202    0        0 eth4
0.0.0.0         10.147.147.5    0.0.0.0         UG    202    0        0 eth3
0.0.0.0         10.147.147.1    0.0.0.0         UG    202    0        0 eth2
0.0.0.0         192.168.251.1   0.0.0.0         UG    202    0        0 eth0
0.0.0.0         10.147.147.1    0.0.0.0         UG    204    0        0 eth2
0.0.0.0         10.147.147.5    0.0.0.0         UG    205    0        0 eth3
0.0.0.0         10.147.147.9    0.0.0.0         UG    206    0        0 eth4
10.147.147.0    0.0.0.0         255.255.255.252 U     204    0        0 eth2
10.147.147.4    0.0.0.0         255.255.255.252 U     205    0        0 eth3
10.147.147.8    0.0.0.0         255.255.255.252 U     206    0        0 eth4
169.254.0.0     0.0.0.0         255.255.0.0     U     203    0        0 eth1
192.168.101.0   0.0.0.0         255.255.255.0   U     0      0        0 eth1
192.168.251.0   0.0.0.0         255.255.255.0   U     202    0        0 eth0
```

Command:
```
./srt-test-live -r 20000 -s 20000 "udp://239.192.101.12:5000/?adapter=192.168.101.104&rcvbuf=$((16*1024*1024))"  "srt://:1234" -v
Multicast: home address: 192.168.101.104:5000
Multicast(POSIX): will bind to IGMP address: 239.192.101.12
Opening SRT target listener(blocking, backlog=1) on :1234
Binding a server on :1234 ...
 listen...  accept...
```

Caller command:
```
 ./srt-test-live srt://185.52.172.21:1234 udp://239.192.192.192:5000 -v
Opening SRT source caller(blocking, backlog=1) on 185.52.172.21:1234
Connecting to 185.52.172.21:1234 ... FAILURE
srt_connect: [1001.0] Connection setup failure: connection timed out
Open FAILED - closing SRT sockets
MEDIA CREATION FAILED: error: srt_connect: Connection setup failure: connection timed out - exiting.
```

The 185.52.172.21 in the caller command is mapped to 10.147.147.2 by the firewall in front of the listener.

There are 3 PCAP files - for eth2 (they contain the 3 requests from the caller but no response), eth3 (this contains one of the 3 responses) and eth4 (this contains the remaining 2 responses).


[pcap-2021-02-02.zip](https://github.com/Haivision/srt/files/5909840/pcap-2021-02-02.zip)

**Comment by ethouris** [comment] 2021-02-04 10:47
I'm really sorry, but these pcaps aren't helpful. I can see in each of them only a few packets (1 to 3) that are being sent from one party to the other party, but there's no response in any of them. I'm not sure what command you used to grab them, however note that the command should trace traffic on the line in both directions.

**Comment by petrn** [comment] 2021-02-04 10:53
@ethouris 

But that is the whole point of this ticket - the connection is NOT established, as the response comes on a DIFFERENT interface and with a different source address then the request came in.

I am not sure it is possible to capture simultaneously from multiple physical interfaces, so that is why you see what you see - the requests are coming over one interface, but the responses are coming from a different one (and it is not even consistent).

There are very few packets, as the caller tries 3 times and then gives up, so you can see the 3 connection requests and the 3 responses, 2 over one and another one over yet another interface.

The commands from both ends (and their output) are included above, the capture corresponds to them.

**Comment by ethouris** [comment] 2021-02-04 11:02
Here is a screenshot in which I have opened all these pcaps. Last time we spoke you said that over at least one device you succeeded to make a single-socket connection. If these pcaps represent the whole traffic, you were unable to make any connection, and the problem is on the UDP system level. 

![image](https://user-images.githubusercontent.com/9600392/106883890-e1af4680-66e0-11eb-9b04-17f608981169.png)

**Comment by ethouris** [comment] 2021-02-04 11:04
Maybe this way: when grabbing the pcaps, try to trace absolutely everything from all devices, just only UDP. In the meantime, of course, try to make sure that no other application is doing any UDP traffic.

**Comment by petrn** [comment] 2021-02-04 11:06
Sorry if this was not clear - I can make a connection using the `srt-test-mpbond` and only when I specify the actual bind address. If I bind the socket to 0.0.0.0 then the connection works in case you set it up from the caller to the address which has the first route in the routing table, it does not work for the remaining 2.

I propose to close this ticket, we seem to be moving in circles, sorry.

**Comment by ethouris** [comment] 2021-02-04 11:08
Maybe, but we still don't know why the two-way UDP link isn't functioning, and your configuration doesn't prove that there's anything wrong there.

**Comment by petrn** [comment] 2021-02-04 11:09
@ethouris that is all the UDP communication on the listener side. The responses never reach the caller as the NAT drops them as the responses are not matching any known connection. That is why the capture needs to be made at the listener side. On the caller, you would see the 3 requests and no response (the same as the upper left window).

**Comment by ethouris** [comment] 2021-02-04 11:11
Wait.... NAT drops them? UDP don't have "connections". Is NAT for UDP configured as bidirectional or not?

**Comment by petrn** [comment] 2021-02-04 11:17
NAT is stateful and it allows responses (reverse of what was sent) to be mapped back to the originator.

So, say you send UDP request to address1 port 1234 and your source port is 5678. This is translated by the NAT to a different source address and a different source port (say, 9876) and the NAT remembers this mapping. When the response comes from address1 source port 1234 and target port 9876, it translates that to the original IP address and port 5678. But if the response comes from another address, the NAT table does not contain any such entry and simply drops the packet. This is the same for - say - DNS request or anything else.

In my case, as this is over LTE, the NAT is a carrier grade NAT done by the mobile operator and I have no control over it.

I believe once you address  #431 and the source address from SRT listener will match that of the destination address in the incoming UDP datagram, it will work.

**Comment by ethouris** [comment] 2021-02-04 11:21
Possibly, but I haven't seen a proof that the behavior is according to the description in #431. I needed these pcaps in order to see the side that receives a packet from one address and then sends them "as a response" back to the wrong address. As we don't know which sides responds to the wrong address, the only way to know it is to grab whole UDP traffic on both sides during the test session.

**Comment by petrn** [comment] 2021-02-04 11:24
all the PCAPs are simultaneous on the listener side. You can correlate them by the timestamps. As this is a test machine and there is no other traffic, what you have in those PCAP files is all there is on the listener side.

As mentioned, the caller side has only the request and no responses (none of the 3 responses come on the interface the request was received on).

So I do not see any point repeating the capture, sorry.

**Comment by ethouris** [comment] 2021-02-04 11:33
Ok, the caller side has only the requests. But I haven't seen as to whether they were received by the listener or not. The key part in resolving this problem is to see that the listener has received and interpreted the handshake packet and has sent something in response. The only possibilities here are:
* the listener received nothing (if so, the problem is in the caller -> listener direction)
* the listener received a handshake packet and has sent a response handshake packet (if so, this is a problem with wrong address OR network transmission in the listener -> caller direction)

No other possibilities (like e.g. the listener has received the packet, but hasn't sent a response) can exist.

To prove that the problem is possible to be fixed in SRT, I need a proof that the listener has received the packet and sent a response. The packet should be visible before NAT translation on the listener host.

**Comment by petrn** [comment] 2021-02-04 11:49
but you do have the responses in the PCAP from interface eth3 and eth4. 

The response to the 1st request on eth2 is the first packet on eth4.
The response to the 2nd request on eth2 is the first packet on eth3.
The response to the 3rd request on eth2 is the 2nd packet on eth4.

IN other words:

request:
09:42:45.375308 IP 88.103.102.37.48624 > 10.147.147.2.1234: UDP, length 64
response:
09:42:45.375389 IP 10.147.147.10.1234 > 88.103.102.37.48624: UDP, length 64

request:
09:42:46.486612 IP 88.103.102.37.48624 > 10.147.147.2.1234: UDP, length 64
response:
09:42:46.486682 IP 10.147.147.6.1234 > 88.103.102.37.48624: UDP, length 64


request:
09:42:47.597414 IP 88.103.102.37.48624 > 10.147.147.2.1234: UDP, length 64
response:
09:42:47.597475 IP 10.147.147.10.1234 > 88.103.102.37.48624: UDP, length 64

**Comment by ethouris** [comment] 2021-02-04 12:15
Ok, do I understand that correctly - all these pcaps come from the same side, listener, just each pcap was grabbed on a separate device, and you don't have logs on the caller?

Is that so that UDP packet is addressed to target 10.147.147.2, it is received by this listener and the listener sends the packet addressed to 88.103.102.37 setting source to 10.147.147.10?

The question is then: why the listener machine thinks that the 88.103.102.37 destination is reachable only through 10.147.147.10 address, and not through 10.147.147.2 ?  Why also exactly the same target address got in the meantime source of 10.147.147.6 address?

What is expected: you should receive packets over ethX device that is configured to the exact IP address as in the target address in UDP, then the source address from which it has come should be used as a destination address, AND the routing rules should decide that to this address you can only send using the ethX device.

This behavior sounds to me as if some kind of link balancing has been configured there, as normally it's not possible that I send 3 packets in a row, all of them to the exactly same address and port and 2 different devices are selected to send them.

One of the reasons why #431 was put aside was that this problem occurs only in "bad network configurations". Your configuration doesn't seem to have this problem as described there, but then it can also prove another case as to why this may lead to this. I need to understand if your network configuration on the UDP level is according to the SRT requirements of having a stable 2-way UDP channel.

**Comment by petrn** [comment] 2021-02-04 12:24
Yes, the 3 logs are all from the listener side.

Yes, you are correct that the 1st packet comes on .2 as the source address and the response goes out on .10 as source address (and therefore through a different interface).

You have the routing table listed in the same response as the PCAP file - there is a route with the same metric for the 3 interfaces (.2, .6 and .10) and as you do not set the source, the kernel seems to use the first 2 in a round-robin or something like that.

There is no link balancing or anything like that configured. But there are multiple default routes, as the listener has no idea from where the caller will connect. My understanding was that only one of these routes will be used, but in this particular case it was using 2 of them. If the metric would be different for all the interfaces (as Debian assigns it by default), then all the responses would be coming out via the interface with the lowest metric.

I think the application (ie. your core library) needs to set the source IP for a response equal to the destination IP on the response. Or you will get what you have seen above. I thought that was the whole point of #431.

I believe in all your tests it probably behaves the same, but as there is no NAT in between in your tests, you never noticed that the responses come on a different interface than the one you have received the request from. You can try to confirm this in your setup (as you are getting the responses, you can make the capture on the caller side).

**Comment by ethouris** [comment] 2021-02-04 12:35
Ok, @J-Rogmann @rndi @maxsharabayko I think we might need to decide something here.

I understand that there wasn't any "balancing configured" here, but allowing multiple route paths to the same address and making the kernel use the one with lowest throughput at the moment is exactly what is called "balancing", even if this wasn't set with that premise. And SRT is unable to work in these conditions. SRT requires a stably configured 1-to-1 bidirectional UDP channel.

That is, you have one machine, which sends A.B.C.D:X -> E.F.G.H:Y, and when that was received by the destination machine, it will send E.F.G.H:Y -> A.B.C.D:X, always. The problem that #431 was trying to solve was that the - STILL FIXED - routing table was selecting incorrect source IP address to send to A.B.C.D:X, **but still configured on the device that should be used**. This is not the case here.

Confirmation that the fix in #431 solves the problem (for a single-socket connections) could be a good start. I personally have doubts that it will work because it may also be that setting the source IP address for sending a packet through a device that doesn't have this IP address set on itself may result in either rejecting this setting or rejecting the packet.

**Comment by petrn** [comment] 2021-02-04 14:01
@ethouris I think I know why you have never really discovered this issue - your assumption would work if all the paths between the caller and listener are "directly connected" - then what you describe would all hold.

But as soon as you have more routing hops between the listener and caller, you will experience what I was facing.

At the moment, the only way to work around it is the trick you suggested with srt-test-mpbond and explicitly binding to the adapter addresses. This means all your examples which use the 0.0.0.0 address for group connection on listener side are not going to work as expected, unless you have the caller directly attached to the listener (same subnet).

**Comment by petrn** [comment] 2021-02-04 14:22
I believe this describes the way it would need to be done. Unfortunately, it is not portable...

https://blog.powerdns.com/2012/10/08/on-binding-datagram-udp-sockets-to-the-any-addresses/

**Comment by ethouris** [comment] 2021-02-04 15:12
> @ethouris I think I know why you have never really discovered this issue - your assumption would work if all the paths between the caller and listener are "directly connected" - then what you describe would all hold.

This isn't "my assumption" - this is a precondition so that SRT can work. SRT can only work with a presumption that the routing rules for UDP for at least that channel that SRT is using are fixed and work bidirectionally. UDP is usually treated by many network configurations as unidirectional protocol for which it doesn't matter if the bidirectional channel functions correctly or that addresses are being also changed in the meantime; many such protocols exist and for them it wouldn't be probably a problem, but SRT isn't one of them.

> But as soon as you have more routing hops between the listener and caller, you will experience what I was facing.

I doubt that because it doesn't change anything in the source/destination specification in the UDP packet header.

> At the moment, the only way to work around it is the trick you suggested with srt-test-mpbond and explicitly binding to the adapter addresses. This means all your examples which use the 0.0.0.0 address for group connection on listener side are not going to work as expected, unless you have the caller directly attached to the listener (same subnet).

It's ok if that's enough to make it work, however it's also interesting for me if setting the explicit IP address to bind the listener causes also sending stably over one particular network device, or this "balancing" would still work. Anyway, as long as one stable source address is put into the outgoing packet (and it's the same as the received destination), this should work fine.

**Comment by mbakholdina** [comment] 2021-04-12 10:34
Closing the ticket due to inactivity. Please feel free to reopen in case of further questions.

**Closed by mbakholdina** 2021-04-12 10:34 UTC
Labels: Type: Question
