### ISSUE TITLE
[BUG] latency higher than configured

### ISSUE THREAD

**Issue by colmaengus** [Haivision/srt#984] opened 2019-11-28 21:35 UTC
**Describe the bug**
The measured latency is higher than configured. Specifically it seems to be 1/2 RTT higher than configured.

I'm using a docker based testbench setup where I'm able to simulate network latency using netem. I've also modified srt-live-transmit to add a timestamp to payload packets before sending and remove them on reception. This allows me to track one way latency.
See attached logs/stats from caller and listener ends: [incorrect-latency.zip](https://github.com/Haivision/srt/files/3903039/incorrect-latency.zip)
For the test I've configured the network latency to be 25ms each way and configured SRT for a latency of 200ms.
In the listener.csv you can see that the latency goes from 201ms to 226ms while the RTT stays constant around 50ms.

I'm using latest SRT from master (46837e) with some changes to srt-live-transmit to calculate latency. The problem is also seen on 1.4.0.

Focussing on packet sequence number 919197455

<details><summary>Click to expand/collapse the logs</summary>
<p>

sender.log
20:08:53.629901/SRT:SndQ:worker D:SRT.d: chn:SENDING SIZE 85 SEQ: 919197455

listener.log
20:08:53.651597/SRT:RcvQ:worker D:SRT.d: ACK: clip %919197454-%919197455, REVOKED 1 from RCV buffer
**latency: 21,696**
20:08:53.651708/SRT:RcvQ:worker D:SRT.c: sendCtrl: %842464802:ACK (1): 919197455
20:08:53.651794/SRT:TsbPd D:SRT.t: NEXT PKT CHECK: rdy=true passack=false skipto=%-1 current=%919197414 buf-base=%919197455
20:08:53.651968/SRT:TsbPd D:SRT.t: NEXT PKT CHECK: rdy=false passack=false skipto=%-1 current=%919197415 buf-base=%919197455
20:08:53.652450/SRT:TsbPd D:SRT.t: NEXT PKT CHECK: rdy=false passack=false skipto=%-1 current=%919197415 buf-base=%919197455
20:08:53.655125/SRT:RcvQ:worker D:SRT.c: INCOMING PACKET: BOUND=0.0.0.0:8000 TARGET=842464802 DATA: msg=4235 seq=919197455 size=85 flags: PB_SOLO ORD_RELAXED EK_NOENC SN_ORIGINAL
20:08:53.655155/SRT:RcvQ:worker D:SRT.d: %842464802:processData: RECEIVED DATA: size=85 seq=919197455
20:08:53.655175/SRT:RcvQ:worker D:SRT.d: addData: unit %919197455 accepted, off=0 POS=4234
20:08:53.655179/SRT:RcvQ:worker D:SRT.c: %842464802:RECEIVED: seq=919197455 offset=0 BUFr=8151 (ACCEPTED/ORIGINAL) FLAGS: PB_SOLO ORD_RELAXED EK_NOENC SN_ORIGINAL
20:08:53.661718/SRT:TsbPd D:SRT.t: NEXT PKT CHECK: rdy=true passack=false skipto=%-1 current=%919197415 buf-base=%919197455
20:08:53.661803/srt-live-transm D:SRT.d: RCV BUF STATS: seqspan=%(919197415-919197455:40) missing=0pkts
20:08:53.661889/srt-live-transm D:SRT.d: RCV BUF STATS: seqspan=%(919197416-919197455:39) missing=0pkts
20:08:53.661950/srt-live-transm D:SRT.d: RCV BUF STATS: seqspan=%(919197417-919197455:38) missing=0pkts
20:08:53.661985/srt-live-transm D:SRT.d: RCV BUF STATS: seqspan=%(919197418-919197455:37) missing=0pkts
20:08:53.662082/SRT:TsbPd D:SRT.t: NEXT PKT CHECK: rdy=false passack=false skipto=%-1 current=%919197419 buf-base=%919197455
20:08:53.662177/srt-live-transm D:SRT.d: RCV BUF STATS: seqspan=%(919197419-919197455:36) missing=0pkts
20:08:53.662519/SRT:TsbPd D:SRT.t: NEXT PKT CHECK: rdy=false passack=false skipto=%-1 current=%919197419 buf-base=%919197455
20:08:53.666254/SRT:RcvQ:worker D:SRT.d: ACK: clip %919197455-%919197465, REVOKED 10 from RCV buffer
20:08:53.810073/srt-live-transm D:SRT.d: RCV BUF STATS: seqspan=%(919197455-919197490:35) missing=0pkts
20:08:53.810085/srt-live-transm D:SRT.c: getRcvReadyMsg: POS=4234 +0 pkt %919197455 NOT ready to play (only in 20.176ms)
20:08:53.810148/SRT:TsbPd D:SRT.c: getRcvReadyMsg: POS=4234 +0 pkt %919197455 NOT ready to play (only in 20.115ms)
**latency: ‭180,247‬ packet is scheduled to play in 20.115ms which would give latency of ~200ms
**
20:08:53.810170/SRT:TsbPd D:SRT.t: NEXT PKT CHECK: rdy=false passack=false skipto=%-1 current=%919197455 buf-base=%919197490
20:08:53.810174/SRT:TsbPd D:SRT.t: %842464802:tsbpd: FUTURE PACKET seq=919197455 T=20:08:53.830260 - waiting 20.086ms
20:08:53.830494/SRT:TsbPd D:SRT.c: getRcvReadyMsg: POS=4234 +0 pkt %919197455 NOT ready to play (only in 24.449ms)
20:08:53.830607/SRT:TsbPd D:SRT.t: NEXT PKT CHECK: rdy=false passack=false skipto=%-1 current=%919197455 buf-base=%919197499
20:08:53.830628/SRT:TsbPd D:SRT.t: %842464802:tsbpd: FUTURE PACKET seq=919197455 T=20:08:53.854935 - waiting 24.311ms
**latency: ‭‭200,727‬‬ packet should be played now but instead is delayed by another 24.311ms** 
20:08:53.855275/SRT:TsbPd D:SRT.c: getRcvReadyMsg: POS=4234 +0 pkt %919197455 ready to play (delayed 0.339ms)
20:08:53.855282/SRT:TsbPd D:SRT.d: getRcvFirstMsg: ready CONTIG packet: %919197455
20:08:53.855286/SRT:TsbPd D:SRT.t: NEXT PKT CHECK: rdy=true passack=false skipto=%-1 current=%919197455 buf-base=%919197506
20:08:53.855290/SRT:TsbPd D:SRT.t: %842464802:tsbpd: PLAYING PACKET seq=919197455 (belated 0.358ms)
20:08:53.855383/srt-live-transm D:SRT.d: RCV BUF STATS: seqspan=%(919197455-919197506:51) missing=0pkts
20:08:53.855405/srt-live-transm D:SRT.c: getRcvReadyMsg: POS=4234 +0 pkt %919197455 ready to play (delayed 0.469ms)
20:08:53.855416/srt-live-transm D:SRT.d: readMsg: DELIVERED seq=919197455 from POS=4234 T=20:08:53.854935 in 0.48ms - TIME-PREVIOUS: PKT: 45.374 LOCAL: 45.401 !142E7AD1
**latency: ‭225,515‬**
 
</p>
</details>

**Comment by maxlovic** [comment] 2019-11-29 11:24
Hi @colmaengus 
The end-to-end latency of SRT is roughly **SRTO_RCVLATENCY + 1/2 × RTT<sub>0</sub>**
Please refer to full description [here](https://maxlovic.github.io/srtcookbook/protocol/tsbpd/latency/).

We need to update the documentation to make it more clear to the comunity.

**Comment by colmaengus** [comment] 2019-11-29 16:25
In your doc you say the e2e latency is roughly SRTO_RCVLATENCY + 1/2 × RTT0. Since the RTT in my simulation isn't changing I'm wondering why the measured e2e latency starts out at SRTO_RCVLATENCY before jumping to SRTO_RCVLATENCY + 1/2 RTT.

**Comment by maxlovic** [comment] 2019-11-29 16:40
What is your netem command?

**Comment by colmaengus** [comment] 2019-11-29 16:42
I'm using delay 25ms 5ms in both directions.

**Comment by colmaengus** [comment] 2019-11-29 21:18
I just realized that the logs I included in the original post were lost in the middle of the text so I've updated the comment. The zip file contains logs with heavy logging and statistics csv files.

**Comment by colmaengus** [comment] 2019-11-29 22:40
Also just realized that my test is doing the SRT handshake before running netem. So the RTT0 would be very low. In your formula above SRTO_RCVLATENCY + 1/2 × RTT0 is the RTT value updated as part of the drift detection by chance? This might explain the jump.

**Comment by maxlovic** [comment] 2019-12-02 09:28
> Also just realized that my test is doing the SRT handshake before running netem. So the RTT0 would be very low. In your formula above SRTO_RCVLATENCY + 1/2 × RTT0 is the RTT value updated as part of the drift detection by chance? This might explain the jump.

Yes, that should be the reason. Also please note that the netem configuration you use also introduces packet reordering. SRT has zero reorder tolerance by default (see `SRTO_MAXLOSSTTL` in [API.md](https://github.com/Haivision/srt/blob/master/docs/API.md)).
Drift tracer has a known issue #753. It does not consider RTT changes. That might cause the behavior you are observing.

**Comment by ethouris** [comment] 2019-12-02 09:35
This `tc` command used here doesn't introduce packet reordering. In order to have reordering you need an extra `reorder` option, which causes that beside the delay imposed on some packets, some packets are sent without delay, which effectively changes the order towards packets that get the delay. Without this option packets are only delayed with some correlation and jitter, but still sent in order.

**Comment by maxsharabayko** [comment] 2019-12-27 11:39
## Summary

### Test Case

1. Establish conenction without netem: `SRTO_RCVLATENCY=200ms`, `RTT0=0`
2. Run netem with `tc qdisc add dev eth0 root netem delay 25ms 5ms` (do the same for receiver and sender).

### Result

Initial end-to-end delay is 201 ms. After running netem the dealy is increased to 226 ms.

### Expected Behavior

Expected end-to-end latency is `SRTO_RCVLATENCY + 1/2 × RTT0`, where `RTT0` is the RTT value during the handshake.

### Reason

Looks related to the bug in Drift Dracer (#753) - RTT changes are wronfully treated as clock drift. 

### Additional Steps to Do

Disable DriftTracer and check that the end-to-end delay remains constant.

**Comment by colmaengus** [comment] 2020-01-28 16:23
I've done some tests looking at how end to end latency varies with RTT. This is done using a modified srt-live-transmit which adds timestamp on ingress and compares it on egress. The testbench is a docker stack using netem to simulate changes in RTT.
The expectation is the end to end latency is independent of changes in RTT after handshake.

![image](https://user-images.githubusercontent.com/6358852/73282031-cd409000-41e8-11ea-8a68-7349cf30f22f.png)

When I remove m_DriftTracer.drift() from inside steady_clock::time_point CRcvBuffer::getPktTsbPdTime I get this which is better but still a slow increase in latency.
![image](https://user-images.githubusercontent.com/6358852/73282430-8901bf80-41e9-11ea-9038-82f18eaa53bd.png)

And here with a single latency jump. It does seem to level out at 155ms
![image](https://user-images.githubusercontent.com/6358852/73282649-de3dd100-41e9-11ea-9bd4-93034b6471be.png)

Am I disabling the DriftTracer in the right way?
Any suggestions as to other things to try?

**Comment by maxsharabayko** [comment] 2020-01-30 14:59
Hi @colmaengus Thanks for sharing. Looks like you've disabled the DriftTracer more or less correctly.
Although the overall latency is weird, but may be.
Will have to postpone this issue for now due to a tight development of network bonding and C++11.

BTW, the end-to-end latency can also be measured by [srt-xtransmit](https://github.com/maxsharabayko/srt-xtransmit/wiki/Use-Cases).
I think you've implemented similar way to write a timestamp into the payload.
Do you add the timestamp on top of the existing payload?

**Comment by colmaengus** [comment] 2020-01-30 16:21
Actually it turns out I didn't disable it properly. It seems there are two contributions from the DriftTracer. One is where the base time is updated using m_DriftTracer.overdrift() in addRcvTsbPdDriftSample and the other is in getPktTsbPdTime.
When I disable both contributions things look much better. It might be worth having mode where the DriftTracer can be disabled until the issue with it is fixed.

![image](https://user-images.githubusercontent.com/6358852/73466870-62bf5980-437a-11ea-8ffb-74403160ed21.png)
![image](https://user-images.githubusercontent.com/6358852/73467053-a914b880-437a-11ea-872b-dfe47c1e7154.png)

Regarding measuring latency that's exactly what we did. I didn't see srt-xtransmit before.
However having it inside srt-live-transmit is useful because you can use it with real video streams.

**Comment by maxsharabayko** [comment] 2020-01-30 16:28
> Actually it turns out I didn't disable it properly. (...) When I disable both contributions things look much better. 

Good! Then it complies with our expectations! Again, thanks for checking!

**Comment by chllcy** [comment] 2020-05-18 03:08
hi, in addRcvTsbPdDriftSample function, ACK-ACK timestamp is RTT/2 ago. but the Calculate used
    const steady_clock::duration iDrift = steady_clock::now() - (getTsbPdTimeBase(timestamp_us) + microseconds_from(timestamp_us));
the RTT/2 is not calculated？

**Comment by ethouris** [comment] 2020-05-18 06:54
The RTT/2 is not included in the calculation of the drift.

**Comment by maxsharabayko** [comment] 2020-05-18 08:06
@chllcy Please refer to the SRT latency description here: [link](https://srtlab.github.io/srt-cookbook/protocol/tsbpd/latency/).
RTT0/2 is included in the initial TSBPD time base value after the handshake, that is why `steady_clock::now() - (getTsbPdTimeBase(timestamp_us)` also include RTT0/2.

**Comment by chllcy** [comment] 2020-05-19 06:45
thanks。
in acceptAndRespond, the m_stats.tsStartTime is greater than 0. but the conclusion packet use 0 timestamp.the later packet will minus m_stats.tsStartTime。

is it need to reset m_stats.tsStartTime = steady_clock::now(); in acceptAndRespond？

**Comment by ethouris** [comment] 2020-05-19 07:57
This is the first possible place to record the start time, and it must be set so that the packet timestamps since this moment can be interpreted or created.

**Comment by maxsharabayko** [comment] 2020-05-20 10:03
> but the conclusion packet use 0 for timestamp

There was a bug #1273  reported recently. @ethouris  It is resolved now, isn't it?

**Comment by ethouris** [comment] 2020-05-20 10:06
Yes, but the bug was because the packet size was set wrong, not because there's a 0 timestamp in the handshake. This is actually intended.

**Comment by maxsharabayko** [comment] 2021-04-29 13:25
Hi @colmaengus, @chllcy  
PR #1965 provides an improvement of the drift tracing. It is under testing.
Would be extremely helpful to get your feedback and test results as well!

**Comment by maxsharabayko** [comment] 2021-08-09 09:54
No further work is expected on this issue, as it was addressed in #1965.
The [API document](https://github.com/Haivision/srt/blob/master/docs/API/API-socket-options.md#SRTO_RCVLATENCY) was also updated with a note on the actual latency **SRTO_RCVLATENCY + 1/2 × RTT<sub>0</sub>**.
Closing.

**Closed by maxsharabayko** 2021-08-09 09:54 UTC
Labels: Type: Bug, [docs]
