### ISSUE TITLE
srt_close() call is blocked for about 3 minutes

### ISSUE THREAD

**Issue by wshvic** [Haivision/srt#305] opened 2018-03-15 02:47 UTC
When we call srt_close(), sometimes it may block for about 3 minutes before function returned, especially when the network condition is not good(we can reroduce it with the network emulator). However, in most good network conditions, this function return immediately.

  I have read the listed issues and don't find someone met the same issue,

**Comment by alexpokotilo** [comment] 2018-03-15 02:55
Do you use sync or async socket mode ?

**Comment by sunphonexs** [comment] 2018-03-15 03:18
How to identify which mode I'm using ? The default mode is sync mode ? We don't change it.

**Comment by alexpokotilo** [comment] 2018-03-15 03:23
We use async mode(check docs for details) and never faced with the problem

**Comment by ethouris** [comment] 2018-03-15 10:13
There were added some changes that should have made sure that all buffers are purged before closing the socket. It was happening in the past that the connection was terminated while there were still data in the sending buffer.

If you are able to reproduce it, please turn on debug logging; this should help us determine the reason. If this was caused by some kind of deadlock, we'll be able to see it in the long stretched times in the log messages.

**Comment by fboucher67** [comment] 2018-03-16 20:38
This is probably due to SRTO_LINGER option.  Disable SRTO_LINGER and problem should not reproduce any more.  Default value of linger is 180 sec which is 3 minutes.

**Comment by sunphonexs** [comment] 2018-03-21 02:02
Problem solved by setting SRTO_LINGER. Thank you all.

**Closed** 2019-08-12 11:08 UTC
Labels: Status: Accepted, Type: Question
