### ISSUE TITLE
[BUG] Negative count in sender buffer observed during long-term test

### ISSUE THREAD

**Issue by ethouris** [Haivision/srt#1395] opened 2020-07-03 09:21 UTC
**Describe the bug**
`addBuffer: size=<negative number>` observed in the logs. Although the count value was less than the size, so the equations with `m_iCount + m_iSize` resulted always positive, it doesn't seem likely to be intended.

The problem has appeared during a long overnight test, and the log file is pretty long, so it's hard to say when it started. It has been seen at the place where a hangup resulting in connection break happened, although it's pretty possible that it was because of the overloaded resources (with writing log file and target stream to a file); still a negative count isn't something that should be expected.

The buffer swells with every packet scheduled for sending and trims with every ACK. This looks like some kind of inconsistency between adding and removing packets from the buffer.

**To Reproduce**
Not known to be reproducible.

**Additional context**
There are logs, but this has been found out in an overnight test and log files are extremely large. There needs to be found a way to extract certain phrases from them without moving or copying them.

**Comment by maxsharabayko** [comment] 2022-09-05 08:59
No steps for reproduction are submitted, and no further bug reports are observed.
Closing as "can't reproduce".

**Closed by maxsharabayko** 2022-09-05 08:59 UTC
Labels: Priority: High, Type: Bug, [core]
