### ISSUE TITLE
High CPU Utilization

### ISSUE THREAD

**Issue by vasudevavarun** [Haivision/srt#554] opened 2019-02-05 09:11 UTC
Hi,

I am facing an issue while using srt over internet, incase of losses in path the srt-live-transmit over-utilizes the machine resulting in utilizing 100% CPU.

**Comment by maxlovic** [comment] 2019-02-05 10:10
Hi @vasudevavarun,
Please specify the version of SRT library and the OS you are on.
Can you suggest steps to reproduce the issue?

**Comment by vasudevavarun** [comment] 2019-02-05 10:19
Hi @maxlovic,
Thank you for the prompt reply. I'm using v1.3.1 on CentOS-7.4-64bit.
Any destination with higher latency or preferably an internet path with losses will do the trick.

**Comment by maxlovic** [comment] 2019-02-05 12:19
@vasudevavarun Can you check [1.3.2-rc.0](https://github.com/Haivision/srt/tree/v1.3.2-rc.0)?

**Comment by vasudevavarun** [comment] 2019-02-05 12:22
@maxlovic Sure, Let me check and get back on this.

**Comment by maxlovic** [comment] 2019-02-05 15:57
Hi @rmsoto,
Are you using `stransmit` as well?
I wonder if this is something about the sample application, or about the library itself.
So, if I just try to connect to a non-existing server, I should see the CPU load increase? Did I undersand you right?

**Comment by rmsoto** [comment] 2019-02-05 16:03
Hi, I´m using v1.3.1 on debian 8.6. We noticed that because we have like "SRT nodes" that act as servers and clients, we have the clients running 24/7 and one of them flooded the CPU triying to connect to its remote server that was down due to HW issues and let the entire machine useless at least 3 times during the last weekend.

**Comment by vasudevavarun** [comment] 2019-02-06 04:41
Hi @maxlovic,
Issue persists in "1.3.2-rc-0" as well.

**Comment by maxlovic** [comment] 2019-02-06 18:50
Thanks for checking and reporting. We'll have it in our list.

**Comment by maxlovic** [comment] 2019-02-07 13:17
Hi @vasudevavarun,

Can you check [this branch](https://github.com/maxlovic/srt/tree/hotfix/stransmit-memleak) please?

**Comment by vasudevavarun** [comment] 2019-02-11 06:03
Hi @maxlovic,
Apologies for replaying late, I got stuck up with some other work.
Since you have merged the hotfix to master branch, I am trying to compile it on CentOS7.4 x86_64 while executing 'make' I am getting the following error.

> CMakeFiles/srt-file-transmit.dir/apps/srt-file-transmit.cpp.o: In function `DoUpload(UriParser&, std::string, std::string)':
> srt-file-transmit.cpp:(.text+0x1762): undefined reference to `std::this_thread::__sleep_for(std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >)'
> collect2: error: ld returned 1 exit status
> make[2]: *** [srt-file-transmit] Error 1
> make[1]: *** [CMakeFiles/srt-file-transmit.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> Linking CXX executable srt-multiplex
> CMakeFiles/srt-multiplex.dir/apps/srt-multiplex.cpp.o: In function `Stall()':
> srt-multiplex.cpp:(.text+0xf7): undefined reference to `std::this_thread::__sleep_for(std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >)'
> CMakeFiles/srt-multiplex.dir/apps/srt-multiplex.cpp.o: In function `MediumPair::TransmissionLoop()::MarkQuit::~MarkQuit()':
> srt-multiplex.cpp:(.text._ZZN10MediumPair16TransmissionLoopEvEN8MarkQuitD2Ev[_ZZN10MediumPair16TransmissionLoopEvEN8MarkQuitD5Ev]+0xce): undefined reference to `std::this_thread::__sleep_for(std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >)'
> CMakeFiles/srt-multiplex.dir/apps/srt-multiplex.cpp.o: In function `MediumPair::TransmissionLoop()':
> srt-multiplex.cpp:(.text._ZN10MediumPair16TransmissionLoopEv[_ZN10MediumPair16TransmissionLoopEv]+0xa2c): undefined reference to `std::this_thread::__sleep_for(std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >)'
> srt-multiplex.cpp:(.text._ZN10MediumPair16TransmissionLoopEv[_ZN10MediumPair16TransmissionLoopEv]+0xb10): undefined reference to `std::this_thread::__sleep_for(std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >)'
> collect2: error: ld returned 1 exit status
> make[2]: *** [srt-multiplex] Error 1
> make[1]: *** [CMakeFiles/srt-multiplex.dir/all] Error 2
> make: *** [all] Error 2

**Comment by vasudevavarun** [comment] 2019-02-11 06:30
Just an update.
Compilation issue was in srt-file-transmit only, I am able to compile srt-live-transmit.
But seems like the problem still persists, I have transmitted to an non-existing IP to replicate the issue and CPU utilization got up to 25% in just 15 minutes time span.

command: ./srt-live-transmit -t:0 -loglevel:note udp://229.1.1.1:2001 srt://xx.xx.xx.xx:3038?latency=2500 -s:5000

**Comment by maxlovic** [comment] 2019-02-11 09:51
Hi @vasudevavarun,
Which version were you building previously on CentOS 7.4?
The call to `this_thread::sleep_for(chrono::milliseconds(250));` is in `srt-file-transfer` at least for a year, and it was in `v.1.3.1`.

I am testing the `srt-live-transmit` from the latest master. I do not see this issue reproduced (after 40 mins).
Can you please recheck with a clean build?

**Comment by vasudevavarun** [comment] 2019-02-11 11:11
@maxlovic,
I am freshly cloned master from yours git, where version.h shows **SRT_VERSION_STRING "1.3.1"**, I am not able to replicate CPU overutilization now, Seems like it is ok but let me observe it for some days in different scenarios.
As for the srt-file-transmit error is still there.

**Comment by maxlovic** [comment] 2019-02-11 11:34
@vasudevavarun,
> As for the srt-file-transmit error is still there.

Which version of gcc are you using? Both `srt-live-transmit` and `srt-file-transmit` can only be built if C++11 support is enabled (see `ENABLE_CXX11` in CMakeLists.txt). Although `srt-live-transmit` probably is not using C++11 features. Looks like your compiler compiled it (so it supports C++11), but the linker has failed to find an implementation in the system libraries. That might be related to the libraries installed on your system.

>  SRT_VERSION_STRING "1.3.1",

Yes, we have not updated the version defined here yet, as it is a Release candidate.

> Seems like it is ok but let me observe it for some days in different scenarios.

I will close the issue for now then. Do not hesitate to reopen if you discover the problem still exists.

Regarding the building errors, please open another issue if you think the problem is still on our side.

**Closed by maxlovic** 2019-02-11 11:34 UTC
Labels: Priority: High, Type: Bug, [apps]
