### ISSUE TITLE
The output UDP will become unstable in about three days by using srt-live-transmit.exe to transmit it.

### ISSUE THREAD

**Issue by Ping-Chih** [Haivision/srt#1163] opened 2020-03-02 06:33 UTC
The SRT caster side:
srt-live-transmit.exe udp://228.0.1.4:8004?adapter=10.10.10.11 srt://220.130.142.139:5204?adapter=192.168.1.5

The SRT receiver side:
srt-live-transmit.exe srt://:5204?adapter=192.168.0.162 udp://192.168.0.162:9998?adapter=192.168.0.162

There is a problem with SRT_1.4.1 using srt-live-transmit.exe to transmit UDP.

The output UDP on the receiver side will become discontinuous in about three days, and its waveform will look like a row of isolated pulses if we use StreamXpert to see the UDP signal.

We tried restarting the srt-live-transmit.exe on the caster side and the srt-live-transmit.exe on receiver side individually to see if the output UDP signal would get back to continuity, and we found that only restarting the receiver will work, again making the UDP signal continuous and a linear waveform with small oscillations amplitudes on StreamXpert.

How to make the output UDP stable for a long time?

The stable status of the output UDP in the beginning of connection (the video is normal on VLC):
![SRT_stable](https://user-images.githubusercontent.com/61678873/75746594-b6480d00-5d55-11ea-8e08-8bc7a79d85fb.jpg)

The output UDP starting to be unstable in about 3 days (the video is abnormal on VLC):
![SRT_unstable](https://user-images.githubusercontent.com/61678873/75746611-c4962900-5d55-11ea-9af1-d0e2ce4fb644.jpg)

**Comment by ethouris** [comment] 2020-03-02 07:38
First of all: did you measure the UDP signal on both sides - the source device and destination device? This is in order to rule out any reasons for this to happen at any place BEFORE srt-live-transmit.

Second - srt-live-transmit has a known problem of not reading fast enough in case of high bitrates; not sure if this is the case here, but I think it might help to use a workaround intended for that case: enlarge the received buffer by adding appropriate `rcvbuf` attribute for UDP URI. You can find more info [here](https://github.com/Haivision/srt/pull/1152).

**Comment by Ping-Chih** [comment] 2020-03-03 03:23
The SRT caster side:
srt-live-transmit.exe udp://228.0.1.4:8004?rcvbuf=67108864?adapter=10.10.10.11 srt://220.130.142.139:5204?adapter=192.168.1.5

The SRT receiver side:
srt-live-transmit.exe srt://:5204?adapter=192.168.0.162 udp://192.168.0.162:9998?rcvbuf=67108864?adapter=192.168.0.162

The source UDP has been confirmed on the source device. There is no problem with the caster source. The bitrate of the transmitted UDP is 10 Mbps.

The stability of the output UDP won't last for one day once rcvbuf=67108864 is added, and there will be nothing seen on VLC, but it is still normal on the caster's VLC.

The SRT caster:
![caster_SRT](https://user-images.githubusercontent.com/61678873/75739656-6f9be800-5d40-11ea-92a3-40c9aae9a0aa.jpg)
![caster_VLC](https://user-images.githubusercontent.com/61678873/75739695-95c18800-5d40-11ea-9370-e8a743586154.jpg)

The SRT receiver:
![receiver_SRT](https://user-images.githubusercontent.com/61678873/75739707-9a863c00-5d40-11ea-9a22-c06080bdf585.jpg)
![receiver_VLC](https://user-images.githubusercontent.com/61678873/75739711-9fe38680-5d40-11ea-86eb-0deb4a2f4577.jpg)

**Comment by Ping-Chih** [comment] 2020-04-15 07:30
The video quality drops along with the unstable stream. Is this an instinct issue to be solved? There is not any lost or dropped packets reported.

**Comment by ethouris** [comment] 2020-04-15 07:36
If there are no lost or dropped packets reported (you might also take a look at possible error logs appearing on standard error output), then please first make sure that your stream isn't damaged BEFORE entering the SRT link.

If the UDP link is to be utilized at the exact same machine where the stream is generated, I'd advice you sending the stream to `srt-live-transmit` through the pipe (using `file://con` as source), and similarly output the stream on the receiver side. The Windows platform is also known of being able to lose UDP packets even within the frames of a single machine.

**Comment by J-Rogmann** [comment] 2020-10-14 10:29
Hello @Ping-Chih 

I had a `srt-live-transmit` running on windows for more than 7 days and did not see any dropped packets on the SRT path. Also the UDP output was looking good to me, but I didn't had detailed statistics on the output. 

I just re-started the test and added `?rcvbuf=67108864` to the URI like you did and will have a closer look at the UDP output this time. I'll let you know, as soon as I find something.

**Comment by maxsharabayko** [comment] 2020-10-19 13:16
See also #1566

**Comment by J-Rogmann** [comment] 2020-10-20 08:45
Hello @Ping-Chih 

It's now running again for almost 4 days and still both outputs are okay and without any glitches or lost packets. I run 2 times `srt-live-transmit` in parallel, 1.4.1 and 1.4.2 version.

Command line sender:
```
.\srt-live-transmit.exe -s 5000 -statsout stats-142-udp2srt.log -pf csv -f udp://:8000?rcvbuf=67108864 srt://:8001
```
Command line receiver:
```
.\srt-live-transmit.exe -s 5000 -statsout stats-142-srt2udp.log -pf csv -f srt://192.168.2.49:8001?rcvbuf=67108864 udp://192.168.2.49:8002
```

I also attached a screenshot, where you can see, that the used network bandwidth is straight as line. I don't see anything going up and down. Looks really stable to me.

Are you trying this on a local machine, or between two computers? Can you try to use unicast instead of multicast, just to isolate a possible error. 

![srt-longterm](https://user-images.githubusercontent.com/47855715/96562090-a66b4200-12c0-11eb-8d19-026b98b535e7.jpg)

**Comment by J-Rogmann** [comment] 2021-01-27 16:11
Hello @Ping-Chih

do you have any updates on this ticket is it solved and can be closed.
Please let us know, if you still need help or how you solved it, in case you found an issue.

best regards,
Justus

**Comment by mbakholdina** [comment] 2021-03-17 11:56
The issue isn't reproducible on our side. Closing the ticket. Feel free to reopen in case of further questions.

**Closed by mbakholdina** 2021-03-17 11:56 UTC
Labels: Type: Question, [apps]
