### ISSUE TITLE
Android Library

### ISSUE THREAD

**Issue by massimoantonini** [Haivision/srt#213] opened 2018-01-08 08:31 UTC
Hi to all. Can anyone tell me if there are any android libraries?

**Comment by ethouris** [comment] 2018-01-16 12:25
Not sure if I get the question.

If you are looking for possibility to compile SRT for Android - this probably isn't yet confirmed, but if you want to try, we'll be happy to fix any problems with this should these arise.

**Comment by sergeiignatov** [comment] 2018-02-02 06:11
Hello,
I followed #109 to build srt library for Android. I'm able do run basic connect/send packet/disconnect scenario.
I have question regarding preferred STL implementation for Android platform. Android NDK r16b offers libc++ and gnustl implementations. I can compile against both libs, but libc++ I got some crashes (for example if I try to srt_connect to wrong ip address, it crashes with SIGABRT).
Did anyone tried srt on Android with libc++ or libc++ on another platform?

**Comment by ethouris** [comment] 2018-02-02 07:56
If you have crashes, then it would be nice if you can describe the problem and share with us through an issue. You can compile with `--enable-debug` so that the call stack for the crash can be obtained, or maybe a debugger can catch the signal before it unwinds the stack.

**Comment by sergeiignatov** [comment] 2018-02-09 02:18
Below are steps to compile for Android using standalone toolchain. Build host is Ubuntu 16.04 LTS Xenial Xerus 64 bit. 

1) Get Android NDK from https://developer.android.com/ndk/downloads/index.html, unzip to /opt. We will use r16b which is latest release for Q1 2018.

2) Create standalone toolchain to build SRT and OpenSSL. In this example we build libs for arm64-v8a ABI. For release app we will repeat build steps with armeabi-v7a, x86 and x86_64 toolchains.

`/opt/android-ndk-r16b/build/tools/make_standalone_toolchain.py -v --arch arm64 --api 21 --stl=libc++ --install-dir=/home/baron/android-toolchain-arm64`

`--arch arm64`: create arm64-v8a toolchain
`--api 21`: Android 5.0, which introduced arm64 support
`--stl=libc++`: Android NDK deprecated gnu compiler and gnustl, so we will go with clang and libc++

3) Google removed openssl from Android 7+. You must build openssl libs by yourself.

OpenSSL 1.0.2n is used. OpenSSL includes and library will be installed to /home/baron/arm64-v8a. Please note `-mandroid` flag removal from `Makefile`. This flag is not required for clang compiler.

```
cd /home/baron/openssl-1.0.2n 

# Add the standalone toolchain to the search path.
export PATH=$PATH:/home/baron/android-toolchain-arm64/bin

# Tell configure what tools to use.
target_host=aarch64-linux-android
export AR=$target_host-ar
export AS=$target_host-clang
export CC=$target_host-clang
export CXX=$target_host-clang
export LD=$target_host-ld
export STRIP=$target_host-strip

# Tell configure what flags Android requires.
export CFLAGS="-fPIE -fPIC"
export LDFLAGS="-pie"

make clean
./Configure android --openssldir=/home/baron/arm64-v8a
sed -i 's/-mandroid//g' Makefile
make
make install
```

4) Build static srt library. 

Modify CMakeLists.txt:
- change install prefix to /home/baron/arm64-v8a (same as for openssl)
- don't use pkgconfig
- set ssl include dirs to /home/baron/arm64-v8a/include, where OpenSSL arm64 is installed
- delete all pthread includes and linker options, Android NDK will add pthread by default
- delete -lrt linker flag

```
#!/bin/sh

cd /home/baron/srt

# Add the standalone toolchain to the search path.
export PATH=$PATH:/home/baron/android-toolchain-arm64/bin

# Tell configure what tools to use.
target_host=aarch64-linux-android
export AR=$target_host-ar
export AS=$target_host-clang
export CC=$target_host-clang
export CXX=$target_host-clang++
export LD=$target_host-ld
export STRIP=$target_host-strip

# Tell configure what flags Android requires.
export CFLAGS="-fPIE -fPIC"
export LDFLAGS="-pie"

git clean -fd
./configure --ENABLE_DEBUG:BOOL=TRUE --ENABLE_SHARED:BOOL=FALSE --ENABLE_CXX11:BOOL=FALSE
make
make install
```

5) Follow https://codelabs.developers.google.com/codelabs/android-studio-cmake/ and create demo app (SRTTest project).

Update build.gradle to use libc++ 
```
        externalNativeBuild {
            cmake {
                abiFilters "arm64-v8a"
                cppFlags "-std=c++11 -frtti -fexceptions"
                arguments "-DANDROID_STL=c++_static"
            }
        }
```
Also we restrict example to "arm64-v8a" only.

Copy `libcrypto.a` and `libsrt.a` to `app\static\arm64-v8a\`

Copy `include` dir to `app\src\main\cpp\`

Modify CMakeLists.txt:

- add includes and libs:

```
add_library(libcrypto STATIC IMPORTED)
add_library(libsrt STATIC IMPORTED)

set_target_properties(libcrypto
                      PROPERTIES
                      IMPORTED_LOCATION
                      ${CMAKE_SOURCE_DIR}/static/${ANDROID_ABI}/libcrypto.a)

set_target_properties(libsrt
                      PROPERTIES
                      IMPORTED_LOCATION
                      ${CMAKE_SOURCE_DIR}/static/${ANDROID_ABI}/libsrt.a)

include_directories(src/main/cpp/include)
```

- link native-lib:

```
target_link_libraries( # Specifies the target library.
                       native-lib
                       libsrt
                       libcrypto
                       ${log-lib} )
```

[CMakeLists.txt](https://github.com/Haivision/srt/files/1709512/CMakeLists.txt)
[SRTTest.zip](https://github.com/Haivision/srt/files/1709522/SRTTest.zip)

**Comment by sergeiignatov** [comment] 2018-02-09 05:32
So far I did only static build with OpenSSL. Will try to build .so too and maybe with gnutls.

@ethouris could you, please, advice how to disable pkg-config for cross-compile environment and how to delete -lpthread and -lrt correctly.
Looks like I should dig deeper into cmake options, like described here https://cmake.org/cmake/help/v3.7/manual/cmake-toolchains.7.html#cross-compiling-for-android-with-a-standalone-toolchain

This is CMakeLists.txt changees: https://gist.github.com/sergeiignatov/80b697cb214b8738ed13572df1ada100

**Comment by ethouris** [comment] 2018-02-09 08:18
With the latest version on `dev` branch the `-lrt` should be already removed. I had last time some issues also with crosscompiling concerning pthread, and this problem should be also already fixed there.

Please don't propose fixes to `master` branch - the `dev` branch has diverged a lot since.

**Comment by ethouris** [comment] 2018-02-09 10:23
Ah, and one more thing - if you need to provide your own compiled version of libssl, I think you **should** be able to do it exactly the "Linux way", that is, have the standard POSIX installation directory, compile the library for the target, and then install it into a root directory where you have all other libraries for the target. For openssl just make sure that all the *.pc files are installed (ROOTDIR/lib/pkgconfig) and this ROOTDIR is given for configure option `--with-target-path`. Then cmake should find OpenSSL automatically.

**Comment by sergeiignatov** [comment] 2018-02-12 00:35
`dev` branch works fine. OpenSSL libraries were installed to `$HOME/arm64-v8a`

`./configure --CMAKE_PREFIX_PATH=$HOME/arm64-v8a --CMAKE_INSTALL_PREFIX=$HOME/arm64-v8a`

**Comment by maxlovic** [comment] 2019-03-08 08:47
Hi @sergeiignatov, @massimoantonini 
Looks like we can close this issue?

**Comment by alexpokotilo** [comment] 2019-03-08 12:20
Hi @maxlovic,
We can close this as well and again there was nothing done in 1.3.3 as android build had already been included to srt more than a year ago.
But again we can close this for sure

**Comment by maxlovic** [comment] 2019-03-08 12:54
@alexpokotilo Thanks for the reply. Closing.

**Closed by maxlovic** 2019-03-08 12:54 UTC
